<a href="https://colab.research.google.com/github/nabilah-afrin/recommendation_system_rokomri_books/blob/secondary/notebooks/Categories_bn_books.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# %cd /content/drive/MyDrive/Rokomari Recommendation Dataset
%cd /content/drive/MyDrive/Dataset/rokomari_books/Rokomari Recommendation Dataset/Datasets

/content/drive/.shortcut-targets-by-id/1SdeIcOv6xY-c8y2UcMwPLYx_BaB0zdXx/Rokomari Recommendation Dataset/Datasets

In [3]:
!ls

 corrected_language.csv        rokomari_book_data_v2.csv	  'scraping log.txt'
'Data Analysis Report.gdoc'    rokomari_books_only_bangla_v2.csv   wrong_language_url.txt
 mixed_title_rokomari_v2.csv   rokomari_v2.csv
 rokomari_book_data.csv        rokomari_v2.ipynb

In [4]:
# !pip install googletrans==4.0.0-rc1
# !pip install googletrans==4.0.0rc1 --quiet

In [5]:
!pip install langdetect -q -q -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 10.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for langdetect (setup.py) ... done

In [6]:
# !pip install -U easynmt

In [7]:
!pip install deep_translator --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 1.7 MB/s eta 0:00:00

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import langdetect as ld
# import googletrans as gt
import deep_translator as dt
from deep_translator import GoogleTranslator

# Only Bangla Books

In [9]:
# load the rokomari_bn_books.csv
df_bn = pd.read_csv("rokomari_books_only_bangla_v2.csv")

# comment mine and uncomment yours
# df_bn = pd.read_csv("/content/drive/MyDrive/Rokomari Recommendation Dataset/df_bn.csv")

In [10]:
df_bn.head(5)

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,n_reviews,price,offer_price,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title
0,350167,অমানুষিক,মনোরঞ্জন ব্যাপারী,একা,Eka (India),পশ্চিমবঙ্গের বই,West Bengal Books,6 March 2023,9789357762298,No summary,...,0,450.0,450.0,https://www.rokomari.com/book/350167/amanushik,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,অমানুষিক,bn
1,377700,নির্বাচিত গল্প সংকলন,লু স্যুন,ছাড়পত্র প্রকাশন (ইন্ডিয়া),Charpatra Prakashan (India),পশ্চিমবঙ্গের বই: সমকালীন গল্প,West Bengal Books: Contemporary Story,Edition,9788194097303,No summary,...,0,320.0,320.0,https://www.rokomari.com/book/377700/nirbachit...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,নির্বাচিত গল্প সংকলন,bn
2,377718,তিমুর ও তার দলবল,আর্কাদি গাইদার,ছাড়পত্র প্রকাশন (ইন্ডিয়া),Charpatra Prakashan (India),পশ্চিমবঙ্গের বই: শিশু-কিশোর উপন্যাস,West Bengal Books: Children and Teens Novel,Edition,9788193860939,No summary,...,0,180.0,180.0,https://www.rokomari.com/book/377718/timur-o-t...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,তিমুর ও তার দলবল,bn
3,189529,চেক ডিসঅনার মামলার সহজ ভাষ্য,মোঃ কাইছার হামিদ,এ.কে লিগ্যাল সল্যুশন,A.K Legal Solution,ব্যাংকিং এন্ড কমার্স ল,Banking and Commerce Law,1st Published,No ISBN,* চেক ডিসঅনার ও মামলা দায়েরের পদ্ধতি সংক্রান্...,...,14,250.0,175.0,https://www.rokomari.com/book/189529/cheque-di...,https://img.cf.rokomari.com/ProductNew20190903...,Not Available,book,5.0,চেক ডিসঅনার মামলার সহজ ভাষ্য,bn
4,325781,হাইকোর্ট এক্সাম ফর্মুলা,মোঃ কাইছার হামিদ,A.K Legal Solution,A.K Legal Solution,Advocacy/ Adjudication Law,Advocacy/ Adjudication Law,Edition,9789843545589,"""High Court Exam Formula"" book will be very he...",...,0,750.0,500.0,https://www.rokomari.com/book/325781/high-cour...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,হাইকোর্ট এক্সাম ফর্মুলা,bn

# Useful Functions

In [11]:
import re
import time
# from easynmt import EasyNMT
# model = EasyNMT('m2m_100_1.2B')
# print(model.translate('Bank Job Entrance Exam Preparation', target_lang='bn'))

def detect_language(row):
    try:
        lang = ld.detect(str(row))
    except:
        return 'unknown'
    return lang

def keep_only_bangla(row):
    """
    The unicode range between \u0980 - \u09FF defines the Bangla characters
    and digits in the Unicode character set
    """
    return re.sub(r'[^-|,|\u0980-\u09FF| ]+', '', str(row)).strip()

def translate_author_names(row):
    text = str(row)
    # time.sleep(8)
    translator = gt.Translator()
    translation = translator.translate(text=text, dest='bn')

    return translation.text

def translate_to_bangla(row):
    return GoogleTranslator(source='auto', target='bn').translate(text=str(row))

def remove_unnecessary_characters(row):
    # pattern = r'[ও|():/, ]+'
    digit_map = str.maketrans('0123456789', '০১২৩৪৫৬৭৮৯')
    text = re.sub(r'[:|ঃ]', ",", str(row))
    # text = re.sub(r'[/]', ", ", text)
    text = re.sub(r'[(|)]', "", text)
    text = re.sub(r'(\s)ও(\s)|(,\s)ও(\s)|(\s)এবং(\s)|/', ', ', text)
    # text = re.sub(r'\sও\s', ', ', text)
    text = re.sub(r'[\d|\d+]', lambda x: x.group(0).translate(digit_map), text)

    return text.strip()

def fix_more_categories_issue(row):
    text = re.sub(r'ক্লাস ৯, ১০', "ক্লাস ৯-১০,", str(row))
    text = re.sub(r"(পাঠ\s)সোহায়িকা|(পাঠো\s)সোহায়িকা|(পাঠের\s)সোহায়িকা", "পাঠ্য সহায়িকা", text)

    return text

In [12]:
# pattern = r'(\s)ও(\s)|(,\s)ও(\s)|(\s)এবং(\s)|/'
text = "শিশু-কিশোরঃ বই এবং (উপন্যাস) ও, কিতাব/পুস্তিকা 0-10, ক্লাস- 1, বইমেলা 2024, 9, 10"
digit_map = str.maketrans('0123456789', '০১২৩৪৫৬৭৮৯')
# # text = "রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার, ও অ্যাডভেঞ্চার: অনুবাদ ও ইংরেজি"
# text = re.sub(r'[:|ঃ]', ",", str(text))
# text = re.sub(r'[/]', ", ", text)
# text = re.sub(pattern, ", ", text)
# text = re.sub(r'[(|)]', "", text)
# text = re.sub(r'(\d+)-(\d+)', lambda x: x.group(0).translate(digit_map), text)
text = re.sub(r'[\d|\d+]', lambda x: x.group(0).translate(digit_map), text)
print(text)
# # text = re.sub(r'(,+)', "", text)
# print(text)

শিশু-কিশোরঃ বই এবং (উপন্যাস) ও, কিতাব/পুস্তিকা ০-১০, ক্লাস- ১, বইমেলা ২০২৪, ৯, ১০

In [13]:
# text = "শিশু-কিশোর: বই এবং (উপন্যাস) ও কিতাব/পুস্তিকা"
# text = "এসএসসি ১ম বর্ষ"
# text = "যখন ৪-৮: গল্প"
# text = re.sub(r'[:]', ",", str(text))
# text = re.sub(r'[/]', ", ", text)
# text = re.sub(r'[(|)]', "", text)
# text = re.sub(r'\sএবং\s', ', ', text)
# text = re.sub(r'\sও\s', ', ', text)
# # text = re.sub(r' ', "", text)
# print(text)

# 2. Categories

In [14]:
df_bn['categories'].nunique()

2163

In [15]:
df_bn['categories'].value_counts().reset_index().loc[:20]

                                           categories  count
0                                         বাংলা কবিতা  21039
1                                     সমকালীন উপন্যাস  12184
2                                     পশ্চিমবঙ্গের বই  10466
3                                        সমকালীন গল্প   6794
4                                     শিশু-কিশোর গল্প   5074
5                                                 ছড়া   2566
6                                      চিরায়ত উপন্যাস   2411
7                                     রোমান্টিক কবিতা   2180
8                                 বিবিধ বিষয়ক প্রবন্ধ   1918
9                            পশ্চিমবঙ্গের বই: প্রবন্ধ   1765
10                সাহিত্যিক, শিল্প ও সংগীত ব্যক্তিত্ব   1636
11                           পশ্চিমবঙ্গের বই: উপন্যাস   1519
12                  সাহিত্য ও সাহিত্যিক বিষয়ক প্রবন্ধ   1512
13                               পশ্চিমবঙ্গের উপন্যাস   1490
14  শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...   1481
15                 পশ্চিমবঙ্গের বই: রচনাসমগ্র ও সংকলন   1414
16                                     অনুবাদ উপন্যাস   1341
17                       পশ্চিমবঙ্গের বই: বাংলা কবিতা   1332
18                                  রোমান্টিক উপন্যাস   1330
19              নবি-রাসুল, সাহাবা, তাবেই ও অলি-আওলিয়া   1282
20                                    নানাদেশ ও ভ্রমণ   1178

In [16]:
df_bn.loc[df_bn['categories'] == "Hadith & Sunnah"]

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,n_reviews,price,offer_price,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title
5212,221841,কাশফুল বারী আম্মা ফি সহিহিল বুখারি ভলিউম ২০ খণ...,শায়খুল হাদিস আল্লামা সালিমুল্লাহ খান র.,Madani Kutubkhana,Madani Kutubkhana,Hadith & Sunnah,Hadith & Sunnah,1st edition,No ISBN,No summary,...,0,750.0,510.0,https://www.rokomari.com/book/221841/kashful-b...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,কাশফুল বারী আম্মা ফি সহিহিল বুখারি ভলিউম ২০ খণ...,bn
5480,244729,আছারুল হাদীস,মাকতাবাতুল হিজায,Maktabatul Hijaz,Maktabatul Hijaz,Hadith & Sunnah,Hadith & Sunnah,No Edition,No ISBN,No summary,...,0,550.0,495.0,https://www.rokomari.com/book/244729/acharul-h...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,আছারুল হাদীস,bn
12475,116623,কুরআনের আলো রোযার হাদীস,মাওলানা মুহাম্মাদ সিরাজুল ইসলাম,Siddikia Publications,Siddikia Publications,Hadith & Sunnah,Hadith & Sunnah,1st Published,9848913629,No summary,...,0,700.0,455.0,https://www.rokomari.com/book/116623/quraner-a...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,কুরআনের আলো রোযার হাদীস,bn
14050,427343,রাসূলুল্লাহ (সাঃ) এর সলাত এবং আক্বীদাহ ও জরুরি...,আল্লামা আবূ মুহাম্মাদ ‘আলীমুদ্দীন (রহ.),Sunan prokasoni,Sunan prokasoni,Hadith & Sunnah,Hadith & Sunnah,3rd Published,No ISBN,জিবরীল (আ) ১০ ওয়াক্ত সলাত পড়ে সলাতের সঠিক পদ্ধ...,...,0,500.0,400.0,https://www.rokomari.com/book/427343/rasululla...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,রাসূলুল্লাহ সাঃ এর সলাত এবং আক্বীদাহ ও জরুরি ম...,bn
17448,428703,সহিহ হাদিসে কুদসী,কামারুজ্জামান বিন আব্দুল মালেক আল-শিবলী আল-আযহারী,Trinolota Prokash,Trinolota Prokash,Hadith & Sunnah,Hadith & Sunnah,1st Published,978984551040,‘সহিহ হাদিসে কুদসী’ হাদিসের নানা বিষয় নিয়ে রচি...,...,0,300.0,270.0,https://www.rokomari.com/book/428703/sahih-had...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,সহিহ হাদিসে কুদসী,bn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203365,423351,মূলনীতিপূর্ণ ১০০ সহীহ হাদীস,মোঃ মাহবুবুর রহমান বিন মুসলেহুদ্দীন,Wahidiya Islamiya Library,Wahidiya Islamiya Library,Hadith & Sunnah,Hadith & Sunnah,1st Published,No ISBN,"ইসলামী শরীয়তের দ্বিতীয় মূল উৎস হল, হাদীস যা কু...",...,0,75.0,58.0,https://www.rokomari.com/book/423351/mulnitipu...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,মূলনীতিপূর্ণ ১০০ সহীহ হাদীস,bn
203380,223656,সহীহ আত-তারগীব ওয়াত তারহীব - ২য় খণ্ড,আল্লামা মুহাম্মদ নাসীরুদ্দীন আলবানী (রহঃ),Wahidiya Islamiya Library,Wahidiya Islamiya Library,Hadith & Sunnah,Hadith & Sunnah,1st Published,No ISBN,সদ্য প্রকাশিত নতুন বই । #সহীহ_আত_তারগীব_ওয়াত_ত...,...,0,750.0,578.0,https://www.rokomari.com/book/223656/sahih-at-...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,সহীহ আততারগীব ওয়াত তারহীব ২য় খণ্ড,bn
203433,407829,হারানো সুন্নাহ,শাইখ ড. মুতলাক বিন জাসির বিন মুতলাক বিন ফারিস ...,Wahidiya Islamiya Library,Wahidiya Islamiya Library,Hadith & Sunnah,Hadith & Sunnah,1st Published,No ISBN,"মানুষ যেসব সুন্নাহর ওপর আমল করা ছেড়ে দিয়েছে, য...",...,1,125.0,96.0,https://www.rokomari.com/book/407829/harano-su...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,5.00,হারানো সুন্নাহ,bn
203446,257543,হাদীস-শাস্ত্রের পারিভাষিক জ্ঞান,শাইখ আব্দুল হামীদ আল-ফাইযী আল-মাদানী,Wahidiya Islamiya Library,Wahidiya Islamiya Library,Hadith & Sunnah,Hadith & Sunnah,1st Published,No ISBN,ইসলামী বই পড়তে গিয়ে আমরা প্রায়শই কিছু পারিভ...,...,0,163.0,126.0,https://www.rokomari.com/book/257543/hadis-sas...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.00,হাদীসশাস্ত্রের পারিভাষিক জ্ঞান,bn
203461,185071,তাহক্বীক্ব রিয়াদুস স্বা-লিহিন,ইমাম মুহিউদ্দীন ইয়াহইয়া আন-নববী (রহ.),Wahidiya Islamiya Library,Wahidiya Islamiya Library,Hadith & Sunnah,Hadith & Sunnah,1st Published,9789849101802,“তাহক্বীক্ব রিয়ায্বুস স্বা-লিহীন” বিষয়ভিত্তিক ...,...,5,825.0,635.0,https://www.rokomari.com/book/185071/tahkwik-r...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,4.75,তাহক্বীক্ব রিয়াদুস স্বালিহিন,bn

## 2.1 Language variations in Categories

In [17]:
df_bn['language_categories'] = df_bn['categories'].apply(detect_language)

In [18]:
df_bn['language_categories'].value_counts()

language_categories
bn    200013
en      2467
id       528
de       356
so       224
af       218
fr       145
tl       112
nl       104
sw        67
ro        63
fi        46
tr        39
es        37
it        25
et        23
hr        20
ca        20
lt        20
cy        15
sq         9
ar         8
vi         6
pt         3
sv         2
no         2
Name: count, dtype: int64

In [19]:
df_bn.loc[df_bn['language_categories'] == 'ar']

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,price,offer_price,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories
68390,381070,কুরআনিক গ্রামার,উম্মে কুলসুম মুনমুন,ঐতিহ্য,Oitijjhya,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,1st Published,9789847762524,লেখক গত দুই বছর ধরে স্ব-উদ্যোগে আল কুরআনরে ভাষ...,...,500.0,430.0,https://www.rokomari.com/book/381070/quranik-g...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,কুরআনিক গ্রামার,bn,ar
91748,221591,আল আদাবুল আরবী ইনদা আলী তানতাভী ১-৩ খণ্ড,ড. শায়খ আলী তানতাবী রাহ.,মাকতাবাতুল আফনান,Maktabatul Afnan,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,1st published,No ISBN,আলী তান্তাভি রচিত আরবি ভাষায় বিভিন্ন প্রবন্ধ য...,...,1000.0,1000.0,https://www.rokomari.com/book/221591/al-adabul...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,আল আদাবুল আরবী ইনদা আলী তানতাভী ১৩ খণ্ড,bn,ar
107459,389931,আল-আযকার,ইমাম আবু যাকারিয়া ইয়াহইয়া বিন শরফ আন-নববী রহ.,জোনাকী প্রকাশনী,Jonaki Prokashoni,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,1st Published,No ISBN,সকল প্রশংসা মহান আল্লাহ রাব্বুল আলামিনের জন্য।...,...,900.0,746.0,https://www.rokomari.com/book/389931/al-azkar,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,আলআযকার,bn,ar
108033,387977,বুখারী শরীফ (১ - ১০ম খন্ড),জননী বুক ডিপো,জননী বুক ডিপো,Jononi Book Depo,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,1st Published,No ISBN,No summary,...,3800.0,1786.0,https://www.rokomari.com/book/387977/bukhari-s...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,বুখারী শরীফ ১ ১০ম খন্ড,bn,ar
111424,393172,আল্লাহ ওয়ালাদের মকবূল মুনাজাত ও তারানা,মাও. ইবরাহীম সেনবাগী,ইত্তিহাদ পাবলিকেশন,Ittihad Publication,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,1st Published,No ISBN,মহান রব্বুল আলামীন বৈচিত্রময় এ বসুন্ধরায় যুগে ...,...,120.0,60.0,https://www.rokomari.com/book/393172/allah-wal...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,আল্লাহ ওয়ালাদের মকবূল মুনাজাত ও তারানা,bn,ar
117017,250650,তারাশে (উর্দূ গল্প),হাকীমুল উম্মত প্রকাশনী,حكيم الامت پركاشني (হাকীমুল উম্মত প্রকাশনী),Hakimul Ummot Prokashoni,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,No Edition,No ISBN,No summary,...,200.0,200.0,https://www.rokomari.com/book/250650/tarashe-u...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,তারাশে উর্দূ গল্প,bn,ar
119831,247636,তাইসীরুল উসুল,মাওলানা মুহাম্মদ নাঈম (হাফিজাহুল্লাহ),গ্রন্থালয়,Gronthaloy,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,No Edition,No ISBN,No summary,...,400.0,220.0,https://www.rokomari.com/book/247636/taisirul-...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,তাইসীরুল উসুল,bn,ar
140063,381526,যাকাত ডায়েরি,শায়খ আব্দুল জাব্বার জাহাঙ্গীর,দারুল হিকমাহ পাবলিকেশন্স লিমিটেড,Darul Hikmah Publications Ltd.,كتب اللغة العربية والأردية (আরবি ও উর্দূ ভাষার...,Arabic & Urdu Languages Books,1st Published,9789848063019,যাকাত সম্পদশালীদের জন্য একটি ফরয ইবাদাত। এটি ই...,...,800.0,688.0,https://www.rokomari.com/book/381526/zakat-diary,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,যাকাত ডায়েরি,bn,ar

In [21]:
df_bn.loc[df_bn['language_categories'] == 'en']

,book_id,title,author,publisher,publisher_name_english,categories,category_english,edition,isbn,summary,...,price,offer_price,book_url,prod_img_link,availability,product_category,actual_rating,bangla_title,language_title,language_categories
4,325781,হাইকোর্ট এক্সাম ফর্মুলা,মোঃ কাইছার হামিদ,A.K Legal Solution,A.K Legal Solution,Advocacy/ Adjudication Law,Advocacy/ Adjudication Law,Edition,9789843545589,"""High Court Exam Formula"" book will be very he...",...,750.0,500.0,https://www.rokomari.com/book/325781/high-cour...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,হাইকোর্ট এক্সাম ফর্মুলা,bn,en
7,313765,ফিরে দেখা ১৯৭১ এর চিঠি ও কথা,ডঃ এ.কে.এম.এ. কাদের,A-Z Foundation,A-Z Foundation,"Diary, Letters and Memories","Diary, Letters and Memories",1st Edition,9789843542939,"The letters, clippings, scribbles, and documen...",...,850.0,731.0,https://www.rokomari.com/book/313765/reminisce...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,5.0,ফিরে দেখা ১৯৭১ এর চিঠি ও কথা,bn,en
23,113881,ঈশান ও তার সুপারহিরো বন্ধুরা,এ. এন. এম নূরুল হক,Adorn Books For Children (ABC),Adorn Books For Children (ABC),Story: Children and Teens,Story: Children and Teens,1st Published,9789842010637,No summary,...,100.0,86.0,https://www.rokomari.com/book/113881/eshan-and...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,5.0,ঈশান ও তার সুপারহিরো বন্ধুরা,bn,en
262,84950,বেহেশ্‌তী জেওর (১ হতে ১১ খণ্ড একত্রে),حكيم الامت مولانا اشرف علي تهانوي رح ( হাকীমুল...,Alif Publications,Alif Publications,Islamic Rules and Regulation and Provisions,Islamic Rules and Regulation and Provisions,1st Published,No ISBN,No Summary,...,450.0,338.0,https://www.rokomari.com/book/84950/beheshti-j...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,বেহেশ্তী জেওর ১ হতে ১১ খণ্ড একত্রে,bn,en
264,85017,মোকছুদুল মোমীনীন বা বেহেশতের পুঞ্জী (সকল খণ্ড ...,মাওলানা খাজা আশরাফ আলী সাহেব,Alif Publications,Alif Publications,Islamic Practices and Guides,Islamic Practices and Guides,1st Published,No ISBN,No Summary,...,500.0,310.0,https://www.rokomari.com/book/85017/moksudul-m...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,1.0,মোকছুদুল মোমীনীন বা বেহেশতের পুঞ্জী সকল খণ্ড এ...,bn,en
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203606,188385,চারিত্রিক সৌন্দর্য কোন পথে?,ছানা উল্লাহ রিয়াদ,আল-ইমাম ফাউন্ডেশন,আল-ইমাম ফাউন্ডেশন,Ideal Lifestyle for Family and Personal,Ideal Lifestyle for Family and Personal,1st Published,No ISBN,No summary,...,60.0,42.0,https://www.rokomari.com/book/188385/charitrik...,https://img.cf.rokomari.com/ProductNew20190903...,Not Available,book,0.0,চারিত্রিক সৌন্দর্য কোন পথে?,bn,en
203607,188386,কুরআন ও আধুনিক বিজ্ঞান,আল্লামা ওবায়দুল্লাহ হামযাহ্,আল-ইমাম ফাউন্ডেশন,আল-ইমাম ফাউন্ডেশন,Islam and Science,Islam and Science,No Edition,No ISBN,No summary,...,40.0,28.0,https://www.rokomari.com/book/188386/quran-o-a...,https://img.cf.rokomari.com/ProductNew20190903...,Not Available,book,0.0,কুরআন ও আধুনিক বিজ্ঞান,bn,en
203608,188384,এসো হে মুমিন জান্নাতের পথে,আল্লামা ওবায়দুল্লাহ হামযাহ্,আল-ইমাম ফাউন্ডেশন,আল-ইমাম ফাউন্ডেশন,Islamic Practices and Guides,Islamic Practices and Guides,1st Published,No ISBN,No summary,...,60.0,42.0,https://www.rokomari.com/book/188384/eso-he-mu...,https://img.cf.rokomari.com/ProductNew20190903...,Not Available,book,0.0,এসো হে মুমিন জান্নাতের পথে,bn,en
204166,432557,"এডমিশন পকেট বুক, ইংলিশ গ্রামার ও লিটারেচার",মোঃ রোকনুজ্জামান সোহেল,Young Bengal Publications,Young Bengal Publications,University Admission Preparation,University Admission Preparation,1st Published,No ISBN,"ঢাবি, রাবি, চবি, জাবি, গুচ্ছ , Ari ( Cluster) ...",...,180.0,180.0,https://www.rokomari.com/book/432557/admission...,https://img.cf.rokomari.com/ProductNew20190903...,Request For Reprint,book,0.0,এডমিশন পকেট বুক ইংলিশ গ্রামার ও লিটারেচার,bn,en
204409,332244,এপারেল মার্চেন্ডাইজিং,হাসান আহমেদ ইমরান,Writer House,Writer House,"Branding, Marketing and Selling","Branding, Marketing and Selling",1st Edition,9789843531209,এপারেল মার্চেন্ডাইজিং বইটি পোশাক শিল্পের মার্চ...,...,1190.0,1107.0,https://www.rokomari.com/book/332244/apparel-m...,https://img.cf.rokomari.com/ProductNew20190903...,Add to Cart,book,0.0,এপারেল মার্চেন্ডাইজিং,bn,en

## 2.2 Fixing categories detected as other language to Bangla and mixed lanugage

### 2.2.1 Fixing categories detected as other language to Bangla

In [22]:
for language in df_bn['language_categories'].value_counts().index:
    if language == 'bn' or language == 'ar':
        continue
    else:
        print(f"Correcting Language: {language}")
        filt = (df_bn['language_categories'] == language, 'categories')
        df_bn.loc[filt] = df_bn.loc[filt].apply(translate_to_bangla)

print("\nDone")

Correcting Language: en
Correcting Language: id
Correcting Language: de
Correcting Language: so
Correcting Language: af
Correcting Language: fr
Correcting Language: tl
Correcting Language: nl
Correcting Language: sw
Correcting Language: ro
Correcting Language: fi
Correcting Language: tr
Correcting Language: es
Correcting Language: it
Correcting Language: et
Correcting Language: hr
Correcting Language: ca
Correcting Language: lt
Correcting Language: cy
Correcting Language: sq
Correcting Language: vi
Correcting Language: pt
Correcting Language: sv
Correcting Language: no

Done

### 2.2.2 Fixing categories with mixed languages with Bangla

In [23]:
filt = (df_bn['language_categories'] == 'ar', 'categories')

In [24]:
df_bn.loc[filt] = df_bn.loc[filt].apply(keep_only_bangla)

In [25]:
df_bn.loc[filt]

68390     আরবি ও উর্দূ ভাষার বই
91748     আরবি ও উর্দূ ভাষার বই
107459    আরবি ও উর্দূ ভাষার বই
108033    আরবি ও উর্দূ ভাষার বই
111424    আরবি ও উর্দূ ভাষার বই
117017    আরবি ও উর্দূ ভাষার বই
119831    আরবি ও উর্দূ ভাষার বই
140063    আরবি ও উর্দূ ভাষার বই
Name: categories, dtype: object

In [29]:
df_bn.loc[df_bn['language_categories'] == 'en', 'categories']

71226     উক্তি, Aphorisms & proverbs
125454    উক্তি, Aphorisms & proverbs
148248    উক্তি, Aphorisms & proverbs
Name: categories, dtype: object

In [33]:
df_bn['language_categories'] = df_bn['categories'].apply(detect_language)
df_bn['language_categories'].value_counts()

language_categories
bn    204572
Name: count, dtype: int64

In [ ]:
# save the modified dataframe

df_bn.to_csv("rokomari_books_categories_corrected.csv", index=False)

## 3 Load the categories corrected dataframe from here

In [ ]:
df_bn = pd.read_csv("rokomari_books_categories_corrected.csv")

### 3.1 Use the Language detection model

In [ ]:
# df_bn['language_categories'] = df_bn['categories'].apply(detect_language)

In [ ]:
df_bn['language_categories'].value_counts()

language_categories
bn    98254
Name: count, dtype: int64

In [35]:
df_bn.loc[df_bn['categories'].str.contains('নবী-রাসূল'), 'categories']

5270      নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
7447      নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
27768     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
27770     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60915     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60921     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60923     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60925     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60926     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60927     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60931     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60933     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60934     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60935     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60937     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
60940     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
76645     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86313     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86315     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86316     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86319     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86327     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86329     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86455     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
86552     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
89451     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
89911     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
90507     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
91614     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
93095     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
93119     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
99255     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
99463     নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
101786    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
114823    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
116742    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
116802    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
125189    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
125193    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
125200    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
137640    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
139941    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
187391    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
188676    নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া
Name: categories, dtype: object

In [36]:
df_bn.loc[df_bn['categories'] == 'নবী-রাসূল, সাহাবা, তাবেয়ী ও অলি-আউলিয়া', 'categories'] = "নবী-রাসুল, সাহাবী, তাবেঈ, ওলি-আউলিয়া"

In [30]:
df_bn.loc[df_bn['language_categories'] == 'fr', 'categories'] = "যখন ৪-৮, উপকথা"

In [31]:
df_bn.loc[df_bn['language_categories'] == 'vi', 'categories'] = "টোফেল"

In [32]:
df_bn.loc[df_bn['language_categories'] == 'en', 'categories'] = "উক্তি, বাণী, প্রবাদ"

### 3.2 Stripping unnecessary characters

In [37]:
df_bn.loc[:, 'categories_fixed'] = df_bn['categories'].apply(remove_unnecessary_characters)

In [38]:
df_bn.loc[:, 'categories_fixed']

0                                           পশ্চিমবঙ্গের বই
1                             পশ্চিমবঙ্গের বই, সমকালীন গল্প
2                       পশ্চিমবঙ্গের বই, শিশু-কিশোর উপন্যাস
3                                    ব্যাংকিং এন্ড কমার্স ল
4                                    অ্যাডভোকেসি, বিচার আইন
                                ...
204567    পশ্চিমবঙ্গের বই, জীবনী, চিঠিপত্র, ডায়েরি, স্মৃ...
204568                                   বাংলা-ইংরেজি কবিতা
204569                                   বাংলা-ইংরেজি কবিতা
204570                                    অতিপ্রাকৃত, ভৌতিক
204571                                          বাংলা কবিতা
Name: categories_fixed, Length: 204572, dtype: object

### 3.2.1 Keeping only the bangla characters

In [39]:
df_bn.loc[:, 'categories_fixed'] = df_bn['categories_fixed'].apply(keep_only_bangla)

In [40]:
# sanity check

df_bn.loc[df_bn['categories'] == ""]

Empty DataFrame
Columns: [book_id, title, author, publisher, publisher_name_english, categories, category_english, edition, isbn, summary, language, rating, n_ratings, n_reviews, price, offer_price, book_url, prod_img_link, availability, product_category, actual_rating, bangla_title, language_title, language_categories, categories_fixed]
Index: []

[0 rows x 25 columns]

In [41]:
df_bn.loc[:, 'categories_fixed']

0                                           পশ্চিমবঙ্গের বই
1                             পশ্চিমবঙ্গের বই, সমকালীন গল্প
2                       পশ্চিমবঙ্গের বই, শিশু-কিশোর উপন্যাস
3                                    ব্যাংকিং এন্ড কমার্স ল
4                                    অ্যাডভোকেসি, বিচার আইন
                                ...
204567    পশ্চিমবঙ্গের বই, জীবনী, চিঠিপত্র, ডায়েরি, স্মৃ...
204568                                   বাংলা-ইংরেজি কবিতা
204569                                   বাংলা-ইংরেজি কবিতা
204570                                    অতিপ্রাকৃত, ভৌতিক
204571                                          বাংলা কবিতা
Name: categories_fixed, Length: 204572, dtype: object

In [42]:
for cat in df_bn.loc[:, 'categories_fixed'].unique():
    print(cat)

পশ্চিমবঙ্গের বই
পশ্চিমবঙ্গের বই, সমকালীন গল্প
পশ্চিমবঙ্গের বই, শিশু-কিশোর উপন্যাস
ব্যাংকিং এন্ড কমার্স ল
অ্যাডভোকেসি, বিচার আইন
প্রোপার্টি ল
ম্যানুয়ালস লস
ডায়েরি, চিঠি, স্মৃতি
চতুর্থ শ্রেণি
ঈমান, আক্বিদা, তাওবাহ
প্রথম শ্রেণি
কিন্ডারগার্টেন, নার্সারি
কিন্ডারগার্টেন, প্লে গ্রুপ
স্মারকগ্রন্থ, বিবিধ
সাহিত্যিক, শিল্প, সংগীত ব্যক্তিত্ব
স্বাস্থ্যবিধি, পরামর্শ
বাংলা কবিতা
সমকালীন উপন্যাস
শিশু, কিশোর কালেকশন
বিবিধ বিষয়ক প্রবন্ধ
গল্প, শিশু, কিশোর
বয়স যখন ০-৪, শিশুতোষ
ভর্তি, নিয়োগ, প্রস্তুতি পরীক্ষা, বিবিধ
জীবনী, স্মৃতিচারণ, বিবিধ
রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার, অ্যাডভেঞ্চার, অনুবাদ, ইংরেজি
শিশু-কিশোর গল্প
ফটোগ্রাফি কৌশল
ছোটদের গণিত, বিজ্ঞান, প্রযুক্তি
কবিতা সমগ্র
চিরায়ত উপন্যাস
পশ্চিমবঙ্গের বই, প্রবন্ধ
পশ্চিমবঙ্গের বই, বাংলা কবিতা
অনুবাদ, আত্ম-উন্নয়ন, মেডিটেশন
পশ্চিমবঙ্গের বই, ভাষা, অভিধান
ইতিহাস, ঐতিহ্য, গবেষণা, প্রবন্ধ
কলকাতা পুস্তকমেলা ২০২৪
পশ্চিমবঙ্গের বই, সংগীত, চলচ্চিত্র, ফটোগ্রাফি
পশ্চিমবঙ্গের বই, সাহিত্য সমালোচনা
পশ্চিমবঙ্গের বই, সাহিত্যিক, শিল্প, সংগীত ব্যক্তিত্ব
পশ্চিমবঙ্গের বই, বিজ্ঞানী
পশ্চিমবঙ্গের বই, প্রবন্ধ, নিবন্ধ, গবেষণা সমগ্র, সংকলন
পশ্চিমবঙ্গের বই, গল্প সমগ্র
পশ্চিমবঙ্গের বই, কলাম সমগ্র, সংকলন
পশ্চিমবঙ্গের বই, সমাজ, সভ্যতা, সংস্কৃতি
পশ্চিমবঙ্গের বই, জীবনী, স্মৃতিচারণ, বিবিধ
পশ্চিমবঙ্গের বই, সাহিত্য, সাহিত্যিক বিষয়ক প্রবন্ধ
পশ্চিমবঙ্গের বই, ইতিহাস, ঐতিহ্য
পশ্চিম বঙ্গের বই, ভ্রমণ, প্রবাস
পশ্চিমবঙ্গের বই, নাটক
পশ্চিমবঙ্গের বই, রাজনীতি
চিরায়ত গল্প
সমকালীন গল্প
বঙ্গবন্ধু শেখ মুজিবুর রহমান
সায়েন্স ফিকশন
সাহিত্য সমালোচনা বিষয়ক প্রবন্ধ
আত্ম-চরিত
রহস্য, গোয়েন্দা
বয়স যখন ৮-১২, গল্প
ডায়েরি, চিঠিপত্র সংকলন
মুক্তিযুদ্ধ, রাজনৈতিক গল্প
বইমেলা ২০২৪
শেখ রাসেল
ভাষা বিষয়ক গবেষণা, প্রবন্ধ, সমালোচনা
জীবনীভিত্তিক উপন্যাস
রেফারেন্স বই
ঐতিহাসিক উপন্যাস
বয়স যখন ১২-১৭, রহস্য, গোয়েন্দা, থ্রিলার, অ্যাডভেঞ্চার
প্রবন্ধ, রবীন্দ্রনাথ
চিরায়ত কাব্য
চিকিৎসা
গল্প সমগ্র
ইসলামি আমল, আমলের সহায়িকা
বয়স যখন ০-৪, প্রাথমিক শিক্ষা
ষ্টেশনারি
সীরাতে রাসূল
নারী সম্পর্কীয়
হজ্জ-উমরাহ, কুরবানি
ইসলামি বিধি-বিধান, মাসআলা-মাসায়েল
মুসলিম ব্যক্তিত্ব
ইসলামি গবেষণা, সমালোচনা, প্রবন্ধ
ইসলামি চিকিৎসা, স্বাস্থ্যবিধি
প্রসঙ্গ, খেলাধুলা
মৃত্যু, পরকাল, জান্নাত-জাহান্নাম
রাজনীতি, রাজনীতিবিদ বিষয়ক প্রবন্ধ
ইসলামী বিধিবিধান, প্রবিধান, বিধান
ইসলামিক অনুশীলন, নির্দেশিকা
উক্তি, বাণী, শ্লোক, প্রবাদ-প্রবচন
জীবনী সংকলন
সমসাময়িক বিষয়ক প্রবন্ধ
ইসলামের ইতিহাস, ঐতিহ্য
ইসলাম প্রসঙ্গ
ইসলামি বিবিধ বই
এসএসসি, সমমান, সাজেশন, টেস্ট পেপারস
কাস্টমস
মহীয়সী নারী জীবনী
অর্থনীতি, ব্যবসা, বানিজ্য ম্যাগাজিন
সাজেশন, কলা বিভাগ
পশ্চিমবঙ্গের বই, শিশু-কিশোর বই
ধর্মীয়, ভক্তিমূলক কবিতা
ইসলামি সওয়াল-জওয়াব
সালাত, নামায
ব্যবসায়ি, উদ্যোক্তা, অর্থনৈতিক ব্যক্তিত্ব
কুরআন বিষয়ক আলোচনা
সমাজ, সভ্যতা, সংস্কৃতি বিষয়ক প্রবন্ধ
প্রাচীন সভ্যতা
নারী, শিশু বিষয়ক প্রবন্ধ
প্রবন্ধ, নিবন্ধ, গবেষণা সমগ্র, সংকলন
বিবিধ ধর্মীয় বই
সমসাময়িক বাংলাদেশ
চলচ্চিত্র, বিনোদন ম্যাগাজিন, মাসিক
ফ্যাশন, রূপচর্চা
পশ্চিমবঙ্গের বই, নারী জীবনী
অনুবাদ উপন্যাস
ইংরেজি ব্যাকরণ, ভাষা শিক্ষা
ইসলাম, সমকালীন বিশ্ব
নাটক
শিশু-কিশোর, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার, অ্যাডভেঞ্চার
মুক্তিযুদ্ধ, ভাষা আন্দোলন, রাজনৈতিক কবিতা
বয়স যখন ৮-১২, রূপকথা, উপকথা, লোককাহিনী
রোমান্টিক উপন্যাস
ছড়া
হাদিস, সুন্নাত
রোমান্টিক কবিতা
বয়স যখন ৮-১২, কমিকস, ছবির গল্প
অনুবাদ গল্প
অনুবাদ কবিতা
বিবিধ বিষয়ক বই
অতিপ্রাকৃত, ভৌতিক
গণমাধ্যম, সাংস্কৃতিক ব্যক্তিত্ব
বয়স যখন ৪-৮, বাংলা ছড়া
থ্রিলার
বয়স যখন ৮-১২, ছড়া
বইমেলা ২০২৩
নারী জীবনী
প্রবন্ধ, কলাম সংগ্রহ, সংকলন
সাহিত্য, সাহিত্যিক বিষয়ক প্রবন্ধ
আবৃত্তি, কলাকৌশল
রাজনৈতিক, মুক্তিযুদ্ধভিত্তিক উপন্যাস
শিশু-কিশোর উপন্যাস
প্রাণী, জীবজগৎ
সাহিত্য ম্যাগাজিন, মাসিক
ওষুধ
বিখ্যাত ব্যক্তি
হিন্দু ধর্মীয় বই
দর্শন বিষয়ক বই
জেলাভিত্তিক সমাজ, সংস্কৃতি
শিশু-কিশোর, সাধারণ জ্ঞান
ঐতিহাসিক ব্যক্তিত্ব, পর্যবেক্ষণ, ঘটনা
পশ্চিমবঙ্গের বই, শিক্ষা, গবেষণা, রেফারেন্স
ব্যাংক চাকরির প্রবেশিকা পরীক্ষার প্রস্তুতি
পশ্চিমবঙ্গের বই, রাজনীতি, ইতিহাস, ঐতিহ্য
ভেষজ, আয়ুর্বেদিক
রাজনৈতিক গবেষণা, প্রবন্ধ
বাংলাদেশ ভ্রমণ
নানাদেশ, ভ্রমণ
আধ্যাত্মিকতা, সুফিবাদ
ইসলামি অনুবাদ বই
মুক্তিযুদ্ধের গল্প
ছবির অ্যালবাম
সাহিত্য ম্যাগাজিন, বিশেষ সংস্করণ
বিজ্ঞানভিত্তিক প্রবন্ধ, গবেষণা, জার্নাল, রেফারেন্স
শিশু-কিশোর, প্রাণী, জীবজগৎ
শিক্ষা, শিক্ষাবিদ বিষয়ক প্রবন্ধ
বয়স যখন ১২-১৭, উপন্যাস
বইমেলা ২০২২
গণমাধ্যম, সাংবাদিকতা বিষয়ক গবেষণা, প্রবন্ধ
গার্মেন্টস, টেক্সটাইল ইঞ্জিনিয়ারিং
বাংলাদেশি আদিবাসী
সাংবাদিকতার কলাকৌশল
অর্থনীতি, ব্যবসা, বানিজ্য ম্যাগাজিন, মাসিক
ইংরেজি বিভাগ, ডিগ্রি ৩য় বর্ষ
প্রসঙ্গ, মুক্তিযুদ্ধ
অ্যাডভেঞ্চার
বিবিধ
সামাজিক, রাজনৈতিক ম্যাগাজিন, মাসিক
রবীন্দ্র সংগীত
সাধারণ জ্ঞান পত্রিকা, বিশেষ সংস্করণ
পশ্চিমবঙ্গের বই, রহস্য, গোয়েন্দা
পশ্চিমবঙ্গের বই, কমিকস, ছবির গল্প
পশ্চিমবঙ্গের বই, গল্প
আন্তর্জাতিক কলকাতা পুস্তকমেলা
পশ্চিমবঙ্গের বই, সমকালীন উপন্যাস
পশ্চিমবঙ্গের বই, কৃষি, কৃষক
কাব্য সমালোচনা
ভাষণ, বক্তৃতা, উপদেশ সংকলন
বাংলাদেশের রাজনৈতিক দল
শিক্ষা, গবেষণা
রাজনৈতিক ব্যক্তিত্ব
ভাষা আন্দোলনের ইতিহাস
কলাম সমগ্র, সংকলন
ঐতিহাসিক ব্যক্তিত্ব
বিপ্লব, বিদ্রোহ
রাজনীতির অনুবাদ বই
দর্শন, দার্শনিক বিষয়ক প্রবন্ধ
অনুবাদ সায়েন্স ফিকশন
সাক্ষাৎকার
বাংলাদেশের রাজনৈতিক ইতিহাস, ঘটনাবলি
বাংলাদেশের রাজনৈতিক ব্যক্তিত্ব
সাধারণ জ্ঞান
বয়স যখন ১২-১৭, জীবনী গ্রন্থ
এইচএসসি ১ম বর্ষ, রসায়ন পাঠ্য বই
মুক্তিযুদ্ধের নানা ঘটনা
সাংবাদিকতা
ইতিহাস, প্রসঙ্গ বাংলাদেশ
অনুবাদ, নাটকের বই
বয়স যখন ৮-১২, কবিতা
মুক্তিযুদ্ধের ডায়েরি, চিঠি, স্মৃতিচারণ
অনুবাদ সাহিত্য সংকলন, সমগ্র
মন, মানসিক, কাউন্সেলিং
স্বাস্থ্য বিষয়ক বিবিধ বই
ভারতীয় উপমহাদেশের ইতিহাস
নাটক সমগ্র
আত্ম উন্নয়ন, মোটিভেশন
ইংরেজি কবিতা
পশু, পাখি বিষয়ক
বিদেশিদের চোখে মুক্তিযুদ্ধ
থিয়েটার, যাত্রা
মুক্তিযুদ্ধের ইতিহাস, শরণার্থী, যুদ্ধাপরাধ, গণহত্যা, নারী, শিশু
সমাজ, সভ্যতা
অঞ্চল, জেলা ভিত্তিক
প্যারেন্টিং
উপন্যাস সমগ্র
বয়স যখন ৪-৮, শিশুতোষ
জেলা, সেক্টর-ভিত্তিক মুক্তিযুদ্ধ
মুক্তিযোদ্ধা, সেক্টরকমান্ডার, সামরিক, বেসামরিক বাহিনী
মুক্তিযুদ্ধের ইতিহাস, প্রবন্ধ, কলাম সংকলন
সমাজ, সভ্যতা, সংস্কৃতি বিষয়ক গবেষণা, প্রবন্ধ
পরিবেশ, প্রকৃতি
নারী, শিশুর স্বাস্থ্য
শিশু-কিশোর, রেফারেন্স, আত্মউন্নয়নমূলক বই
অতিপ্রাকৃত, ভৌতিক উপন্যাস
ভূগোল, পরিবেশ বিদ্যা
শিশু বিকাশ, স্বাস্থ্য, পুষ্টি, পরিচর্যা
কবিতা- বাংলা
শেখ হাসিনা
শিশু-কিশোর, বিবিধ
বয়স যখন ৪-৮, গল্প, কাহিনী
রম্য গল্প
শিশু-কিশোর সাহিত্য, রচনা সমগ্র
স্বাধীনতা উত্তর বাংলাদেশ
বয়স যখন ৮-১২, ভৌতিক
মুক্তিযুদ্ধের ছড়া-কবিতা
মুক্তিযুদ্ধের উপন্যাস
এইচএসসি ২য় বর্ষ, ফিন্যান্স, ব্যাংকিং, বিমা পাঠ্য বই
এইচএসসি ১ম বর্ষ, ফিন্যান্স, ব্যাংকিং, বিমা পাঠ্য বই
এইচএসসি ১ম বর্ষ, পৌরনীতি পাঠ্য বই
এইচএসসি, ঐচ্ছিক বিষয়
ইসলামি উপন্যাস
কৌতুক
মৎস্য চাষ
মাইক্রোসফট অফিস
বয়স যখন ৪-৮, শিক্ষামূলক
বাংলাদেশ বিষয়ক প্রবন্ধ
অন্যান্য চাকরির প্রস্তুতি
ছাত্রজীবন উন্নয়ন
পেশাগত স্মৃতিচারণ, অভিজ্ঞতা
থ্রিলার, অ্যাডভেঞ্চার উপন্যাস
পশ্চিমবঙ্গের বই, আত্ম-উন্নয়ন, মেডিটেশন
পশ্চিমবঙ্গের বই, অতিপ্রাকৃত, ভৌতিক
পশ্চিমবঙ্গের বই, থ্রিলার
পশ্চিমবঙ্গের বই, জীবনী, চিঠিপত্র, ডায়েরি, স্মৃতিচারণ, সাক্ষাৎকার
সপ্তম শ্রেণি
অষ্টম শ্রেণি
ষষ্ঠ শ্রেণি
নবম, দশম এসএসসি, আবশ্যিক বিষয়
নবি-রাসুল, সাহাবা, তাবেই, অলি-আওলিয়া
পশ্চিমবঙ্গের বই, ধর্ম বিষয়ক
সিভিল ইঞ্জিনিয়ারিং
বিজ্ঞান, তথ্য-প্রযুক্তি বিষয়ক প্রবন্ধ
মহাকাশ বিজ্ঞান, জ্যোতির্বিদ্যা
বিজ্ঞানী
ইঞ্জিনিয়ারিং চাকরি
শব্দভান্ডার
ফিনান্স বিভাগ
দোয়া, দরূদ, যিকর
দাওয়াত, তাবলীগ, বক্তৃতা, আলোচনা, ওয়াজ
ইসলামি আইন, ফতোয়া, ফিকহ শাস্ত্র
ইসলামি সাহিত্য
ডায়েরি, চিঠি সংগ্রহ
দুই, দরূদ, যিকর
কম্পিউটার, আইটি ম্যাগাজিন
নাট্য সমালোচনা, অন্যান্য
ভর্তি, নিয়োগ কালেকশন
প্রিলিমিনারি
ইংরেজি ভাষা, সাহিত্য
বাংলা ভাষা, সাহিত্য
অন্যান্য দক্ষতা বৃদ্ধি
গাণিতিক যুক্তি
প্রাথমিক
প্রাইমারি প্রিলিমিনারি
বাংলা, ইংরেজি, গণিত
বিসিএস
মুক্তিযুদ্ধের ইতিহাস, প্রসঙ্গ মুক্তিযুদ্ধ
রোমান্টিক গল্প
বয়স যখন ১২-১৭, রচনাসমগ্র, সংকলন
রচনা সংকলন, সমগ্র
বয়স যখন ৮-১২, উপন্যাস
ভাষা বিষয়ক বিবিধ বই
বয়স যখন ১২-১৭, গণিত, বিজ্ঞান, প্রযুক্তি
বয়স যখন ১২-১৭, নাটক
বাংলাদেশের জেলা, অঞ্চল ভিত্তিক ইতিহাস
যুদ্ধাপরাধ, গণহত্যা, শরণার্থী, নারী, শিশু
প্রবন্ধ, সমগ্র, সংকলন
বয়স যখন ৪-৮, কমিক্স, ছবির গল্প
ভ্রমণ কালেকশন
বাংলা ব্যাকরণ, ভাষা শিক্ষা
বয়স যখন ৮-১২, জীবনী গ্রন্থ
মুক্তিযুদ্ধের প্রবন্ধ, কলাম সংকলন
পরিবেশ, প্রকৃতি, প্রবন্ধ, অন্যান্য
সায়েন্স ফিকশন গল্প
লোক সংগীত
সায়েন্স ফিকশন সমগ্র, সংকলন
শিশুদের নাম
বিবিধ রাজনৈতিক বই
আর্ট, সংস্কৃতি, ঐতিহ্য বিষয়ক প্রবন্ধ
প্রসঙ্গ, বাংলাদেশের রাজনীতি
সংগীত সংগ্রহ
ফটোগ্রাফি বিষয়ক প্রবন্ধ, সমালোচনা
মুক্তিযুদ্ধের ইতিহাস, সামরিক, বেসামরিক বাহিনী
শিক্ষা, শিক্ষাবিদ সম্পর্কে নিবন্ধ
সংগীত, বিবিধ
ব্যঙ্গ, রম্যরচনা
বয়স যখন ১২-১৭, গল্প
বয়স যখন ১২-১৭, ভাষা আন্দোলন, মুক্তিযুদ্ধ
মুক্তিযুদ্ধভিত্তিক অনুবাদ, ইংরেজি সাহিত্য
মুক্তিযুদ্ধের ইতিহাস, ডায়েরি, চিঠি, স্মৃতিচারণ
বাংলাদেশের পরিবেশ, প্রকৃতি
শিশু-কিশোর, রচনাসমগ্র, সংকলন
বয়স যখন ৪-৮, রূপকথা, উপকথা, লোককাহিনী
বাংলাদেশ বিষয়ক গবেষণা, প্রবন্ধ, পরিসংখ্যান
মুক্তিযোদ্ধা, সেক্টর কমান্ডার, সামরিক, বেসামরিক বাহিনী
শিশু-কিশোর, ছড়া
কবিতা সংকলন, সমগ্র
রহস্য, ভৌতিক, থ্রিলার, অ্যাডভেঞ্চার সমগ্র, সংকলন
মুক্তিযুদ্ধের ইতিহাস, মুক্তিযুদ্ধের নানা ঘটনা
রম্য সাহিত্য
জীবন, জীবিকা, সংস্কৃতি
ইতিহাস, শিল্পকলা, সাহিত্য
বয়স যখন ৮-১২, পরিবেশ, প্রকৃতি
ভ্রমণ, প্রবাস, বিবিধ
বয়স যখন ৪-৮, গল্প
রাজনৈতিক ষড়যন্ত্র, হত্যাকাণ্ড
বাংলা ব্যাকরণ
বিষয় ভিত্তিক অভিধান
প্রবাস জীবন
মুক্তিযুদ্ধের ইতিহাস, মুক্তিযুদ্ধ, রাজনীতি
ব্যাংকিং, ফিন্যান্স
ব্যায়াম, ডায়েট
পশ্চিমবঙ্গের বই, বিবিধ বই
সাধারণ জ্ঞান ম্যাগাজিন, মাসিক
হাদিস বিষয়ক আলোচনা
পরিবারের জন্য আদর্শ জীবনধারা
ইসলামিক আদর্শ
মৃত্যু, পরকাল, স্বর্গ-নরক
সালাহ
ঈমান, বিশ্বাস, তাওবাহ
ইসলামিক গবেষণা, সমালোচনা, প্রবন্ধ
ইসলামি বই, আত্ম উন্নয়ন
নারী সম্পর্কে
মুসলিম সভ্যতা, সংস্কৃতি
দাওয়াত, তাবলীগ, বক্তৃতা, বক্তৃতা
হাদিস নিয়ে আলোচনা
ইসলামি বই, আত্ম-উন্নয়ন
অনুবাদ, তাফসীর
পশ্চিমবঙ্গের বই, কবিতা
পর্বতারোহণ, ট্রেকিং গাইড
পশ্চিমবঙ্গের বই, স্মৃতিচারণ, স্মারক, সাক্ষাৎকার
পশ্চিমবঙ্গের বই, উপন্যাস
পশ্চিমবঙ্গের রচনা সংকলন, সমগ্র
পশ্চিমবঙ্গের বই, শিশু-কিশোর গল্প
শিশু কিশোর ম্যাগাজিন
কমিক্স বই
পশ্চিমবঙ্গের বই, ব্যবসা, বিনিয়োগ, অর্থনীতি
পশ্চিমবঙ্গের বই, রম্যরচনা
পশ্চিমবঙ্গের বই, অনুবাদ, আত্ম-উন্নয়ন, মেডিটেশন
আইন সম্পর্কিত বিবিধ বই
বয়স যখন ১২-১৭, ধর্মীয় বই
দেশি ম্যাগাজিন
আন্তর্জাতিক রাজনীতি
আন্তর্জাতিক বিষয়ক প্রবন্ধ
ভারত ভ্রমণ
ধর্ম, ধর্মীয় ব্যক্তি বিষয়ক প্রবন্ধ
সাধারণ বিজ্ঞান
প্রাথমিক প্রাথমিক
রাজনৈতিক কলাম, প্রবন্ধ
পশ্চিমবঙ্গের বই, ছড়া
পূর্ব-এশীয় ভাষা
আধুনিক গান
শিশু-কিশোর, গণিত, বিজ্ঞান, প্রযুক্তি
ক্রীড়া ব্যক্তিত্ব
প্রসঙ্গ বাংলাদেশ
সমাজ, সভ্যতা, সংস্কৃতি, প্রসঙ্গ বাংলাদেশ
অর্থনীতি প্রসঙ্গ বাংলাদেশ
অনুবাদ, ইংরেজি ড্রয়িং, পেইন্টিং
শিশুতোষ গ্রন্থ
পশ্চিমবঙ্গের বই, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার, অ্যাডভেঞ্চার
পশ্চিমবঙ্গের বই, ছড়া, কবিতা
পশ্চিমবঙ্গের বই, রচনাসমগ্র, সংকলন
সংগীত বিষয়ক আলোচনা
পশ্চিমবঙ্গের বই, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার, অ্যাডভেঞ্চার সমগ্র, সংকলন
পশ্চিমবঙ্গের বই, দার্শনিক
পশ্চিমবঙ্গের বই, ঐতিহাসিক ব্যক্তিত্ব
পশ্চিমবঙ্গের বই, রকমারি কালেকশন
পশ্চিমবঙ্গের বই, রোমান্টিক কবিতা
পশ্চিমবঙ্গের বই, গণিত, বিজ্ঞান, প্রযুক্তি
পশ্চিমবঙ্গের বই, গণমাধ্যম, সাংবাদিকতা
প্রসূতি, স্ত্রীরোগবিদ্যা
ব্যাংক চাকরি নিয়োগ প্রস্তুতি
লেবার , সার্ভিস লস
বয়স যখন ৮-১২, ধর্মীয় বই
আবহাওয়া পরিবেশ, জলবায়ু
যখন ৮-১২, পরিবেশ, প্রকৃতি
রহস্য,গোয়েন্দা,ভৌতিক, থ্রিলার কালেকশন
রহস্য, গোয়েন্দা উপন্যাস
শিশু-কিশোর, বিখ্যাত ব্যক্তি, জীবনী
বিজ্ঞান প্রজেক্ট
ক্যারিয়ার উন্নয়ন
মুক্ত গদ্য
ভৌতিক, অতিপ্রাকৃত গল্প
গণিত, বিজ্ঞান, প্রযুক্তি, বিবিধ
হিন্দু ধর্মীয় ব্যক্তিত্ব
গুপ্ত গোষ্ঠী, সংগঠন
উদ্যোক্তা
কর্মক্ষেত্রের স্মৃতি, অভিজ্ঞতা
ব্যবসা, বিনিয়োগ
ডিপ্লোমা ইন ইঞ্জিনিয়ারিং
বিদেশী লাইফ স্টাইল ম্যাগাজিন
আইকিউ, ধাঁধাঁ, বুদ্ধির খেলা,
ইসলামি গল্প
কখন ৪-৮, ধর্মীয় বই
গণিত
সীরাতে রাসুল সা
বিশ্ববিদ্যালয় ভর্তি প্রস্তুতি
বিজ্ঞান বিভাগ ভর্তি প্রস্তুতি
বিশ্ববিদ্যালয় ভর্তি প্রস্তুতি
পরিবার, প্যারেন্টিং, শিশু বিষয়ক অন্যান্য বই
হোমিওপ্যাথি
দর্শন বিষয়ক গবেষণা, প্রবন্ধ
ইসলাম ধর্মীয় ব্যক্তিত্ব
ইসলামি ইতিহাস, ঐতিহ্য
হোমিওপ্যাথিক
মেডিটেশন, ইয়োগা
কওমি, নার্সারী, শিশু শ্রেণি
মাদ্রাসার বই
অঙ্কন, পেইন্টিং
বাংলাদেশের সমাজ, সংস্কৃতি
গল্প সংকলন, সমগ্র
বয়স যখন ৪-৮, সাধারণ জ্ঞান
ব্র্যান্ডিং, মার্কেটিং, সেলিং
ব্যবস্থাপনা, নেতৃত্ব
ব্যাংকিং ডিপ্লোমা
মেডিক্যাল ভর্তি প্রস্তুতি
ফ্যাশন, রূপচর্চা ম্যাগাজিন
ইঞ্জিনিয়ারিং নিয়োগ
তৃতীয় শ্রেণি
ইসলামি অর্থনীতি, ব্যবসা বাণিজ্য
স্বরলিপি
কওমি মাদ্রাসার বিবিধ বই
এশিয়ার ইতিহাস
মুঘল সাম্রাজ্যের ইতিহাস
ইতিহাস, ঢাকা
চলচ্চিত্র সমালোচনা
বয়স যখন ৪-৮, ভৌতিক
প্রাচীন বাংলার ইতিহাস
নৃত্য বিষয়ক বই
মুক্তিযুদ্ধের ইতিহাস, গণমাধ্যমে মুক্তিযুদ্ধ
চিকিৎসক
বয়স যখন ৮-১২, রেফারেন্স, আত্মউন্নয়নমূলক বই
নারী মুক্তিযোদ্ধা, বীরাঙ্গনা
পদার্থবিজ্ঞান
কিশোর-কিশোরীর স্বাস্থ্য
বয়স যখন ৮-১২, রচনাসমগ্র, সংকলন
ইতিহাস সম্পর্কিত অনুবাদ বই
ক্ষুদ্র, মাঝারি ব্যবসায় উদ্যোগ
ইতিহাস, ইতিহাসবিদ বিষয়ক প্রবন্ধ
সমাজসেবক, সংস্কারক
ইসলামি আদর্শ, মতবাদ
বাংলাদেশ সম্পর্কিত বই
রাজনৈতিক সমালোচনা, কলাম সংকলন
রহস্য, গোয়েন্দা গল্প
জেলা, সেক্টর ভিত্তিক মুক্তিযুদ্ধ
ফ্রিল্যান্সিং, আউটসোর্সিং
চাকুরি পাওয়ার কৌশল
রহস্য, গোয়েন্দা
জীবনী, স্মৃতি, অন্যান্য
আত্ম-উন্নয়ন, মেডিটেশন কালেকশন
জীবনী, স্মৃতিচারণ কালেকশন
শিশু-কিশোর, ভাষা আন্দোলন, মুক্তিযুদ্ধ
ভ্রমণ বিষয়ক স্মৃতি
বয়স যখন ৮-১২, রহস্য, গোয়েন্দা, থ্রিলার, অ্যাডভেঞ্চার
ঐতিহাসিক গল্প
অস্ট্রেলিয়া ভ্রমণ
আমেরিকা ভ্রমণ
মুক্তিযুদ্ধের ইতিহাস, জেলা, সেক্টর ভিত্তিক
শিশু-কিশোর, রূপকথা, উপকথা, লোককাহিনী
স্বাধীনতা পূর্ব বাংলাদেশ
বাংলাদেশ, ইতিহাস
গণতন্ত্র
শিশু-কিশোর, ইতিহাস, রাজনীতি
ঔপনিবেশকাল, ভারত বিভাগ
মুক্তিযুদ্ধকালীন ইতিহাস
সংগীত ব্যক্তিত্ব
ব্যবসা, অর্থনীতি বিষয়ক প্রবন্ধ, গবেষণা, পরিসংখ্যান
মুক্তিযুদ্ধের দলিল, গবেষণাপত্র
প্রসঙ্গ ইতিহাস
বয়স যখন ৮-১২, গণিত, বিজ্ঞান, প্রযুক্তি
বাংলা বিভাগ, অনার্স ১ম বর্ষ
উপস্থাপনা, বক্তৃতা, বিতর্কের কলাকৌশল
কৃষি বিষয়ক প্রবন্ধ, বিবিধ
বিজ্ঞান, প্রযুক্তি
গণিত অলিম্পিয়াড প্রাইমারি
জীবনদর্শন
সভ্যতার বিকাশ, বিবর্তন
পুঁজিবাদ
সিভিল প্রসিউডর এন্ড প্র্যাক্টিস ল
বহির্বিশ্বের আদিবাসী
শিশু-কিশোর, রম্য, ব্যঙ্গ রচনা
প্রাচীন সভ্যতার ইতিহাস
রান্না, খাদ্য, পুষ্টি বিষয়ক বিবিধ বই
শিশু-কিশোর, পরিবেশ, প্রকৃতি
শিশু-কিশোর, গল্প
ঢাকা
ব্যবসা, বিনিয়োগ, অর্থনীতি বিষয়ক বিবিধ বই
অর্থনীতি
শিশু-কিশোর, রহস্য, গোয়েন্দা, থ্রিলার, অ্যাডভেঞ্চার
৯০ এর দশক, সমসাময়িক বাংলাদেশ
তত্ত্ব, দর্শন, বিবিধ মতবাদ
শিশু-কিশোর, ভৌতিক
রেসিপি
সাংবাদিকতা, প্রতিবেদন
কবিতা সংকলন
ব্যাংকিং, ফিনান্স
বয়স যখন ১২-১৭, সায়েন্স ফিকশন
ছাত্র জীবনের স্মৃতিচারণ
প্রফেশনাল, জার্নাল, রেফারেন্স, বিবিধ
চলচ্চিত্রের কারিগরি কৌশল
রেনেসাঁ
খেলার নিয়ম কানুন
মিশরীয় সভ্যতা
ইসলামের বিশেষ দিন, ঘটনাবলি
পারিবারিক জীবনবিধান
বাংলা-ইংরেজি কবিতা
গাঁথা,  গীতি কবিতা
ট্র্যাভেল ম্যাগাজিন
রাজনৈতিক দ্বন্দ্ব, যুদ্ধবিগ্রহ, গণহত্যা
ভ্রমণ উপন্যাস
বৌদ্ধ ধর্মীয় বই
কবিতা
মুক্তিযুদ্ধের ইতিহাস
চলচ্চিত্র, বিনোদন ম্যাগাজিন, বিশেষ
দেশি জার্নাল
চলচ্চিত্র, বিনোদন
পৌরাণিক, কিংবদন্তী
দেশি রেসিপি
গণমাধ্যম, মুক্তিযুদ্ধ
গ্রীক সভ্যতা
হিউম্যান রিসোর্স ম্যানেজমেন্ট
কর্পোরেট ল
বাদ্যযন্ত্র, সঙ্গীত
বয়স যখন ৪-৮, ছবি আঁকা
শেয়ারবাজার, ব্যবসা, বিনিয়োগ
সার্ভিস লস
প্রামাণ্য আইন
পশ্চিমবঙ্গের বই, ঐতিহাসিক উপন্যাস
পশ্চিমবঙ্গের বই, রান্নার বই
পশ্চিমবঙ্গের বই, ক্রীড়া ব্যক্তিত্ব
যখন ৪-৮, শেখা
জামাতে তাইসির
হাদিস, সুন্নাহ
আরবি ব্যাকরণ
কওমি, ক্লাস সেভেন
কওমি, ক্লাস সিক্স
কওমি, কেজি, ক্লাস ওয়ান
কওমি, ক্লাস থ্রি
কওমি মাদ্রাসা
কওমী মাদ্রাসার বিভিন্ন বই
জামায়াত হেদায়াতুন্নাহু
উলুমুল হাদীস বিভাগ
বিভিন্ন ধর্মীয় বই
কওমি, পঞ্চম শ্রেণি
জামাতে মিযান
ফতোয়া ইফতা বিভাগ
অনুবাদ, পুরস্কারপ্রাপ্ত বই
জামাতে হেদায়াতুন্নাহু
জামাতে নাহবেমির
নবী-রাসুল, সাহাবী, তাবেঈ, ওলি-আউলিয়া
জামাতে শরহে বেকায়া
কওমি, ক্লাস ফাইভ
দাওরায়ে হাদীস
মিজান জামাত
জামাত জালালাইন
জামাত মেশকাত
কওমি, ক্লাস টু
কওমি, ক্লাস ফোর
কওমি, ক্লাস এইট
কওমি, নার্সারি, শিশু শ্রেণি
ব্যক্তিগত, পারিবারিক জীবনবিধান
জামাতে কাফিয়া
কওমি, তৃতীয় শ্রেণি
জামাতে শরহে জামি
কওমি, অষ্টম শ্রেণি
ধর্মীয় বই, প্যারেন্টিং
ব্যক্তিগত জীবনবিধান
আরবি, উর্দু ভাষার বই
কওমি, ষষ্ঠ শ্রেণি
কওমি, সপ্তম শ্রেণি
কওমি, চতুর্থ শ্রেণি
জামাতে মেশকাত
বয়স যখন ৪-৮, ধর্মীয় বই
ইসলাম শিক্ষা বিভাগ, অনার্স ১ম বর্ষ
দর্শন বিভাগ, অনার্স ১ম বর্ষ
বিষয়ভিত্তিক দর্শন
ইসলামি দর্শন
আরবি শিক্ষা
এইচএসসি ১ম বর্ষ, ব্যবসায় সংগঠন, ব্যবস্থাপনা পাঠ্য বই
এইচএসসি ২য় বর্ষ, গণিত পাঠ্য বই
এইচএসসি ১ম বর্ষ, গণিত পাঠ্য বই
এইচএসসি ১ম বর্ষ, হিসাববিজ্ঞান পাঠ্য বই
সংগীত, চলচ্চিত্র, বিনোদন বিষয়ক প্রবন্ধ
ভাষা আন্দোলন
চলচ্চিত্র বিষয়ক প্রবন্ধ, আলোচনা
বেসিক কম্পিউটার
পঞ্চম শ্রেণি পিইসি
যখন ০-৪, প্রাথমিক শিক্ষা
খ্রিস্টান ধর্মীয় বই
ইসলামি স্থাপত্য, সংস্কৃতি
যখন ৪-৮, শিশুসুলভ
কখন ৪-৮, ছড়া, কবিতা
শিশুদের জন্য কম্পিউটার শেখার বই
বাংলাদেশ, বিবিধ প্রসঙ্গ
কম্পিউটার, ইন্টারনেট, ফ্রিল্যান্সিং, আউটসোর্সিং বিষয়ক বিবিধ বই
শিশু-কিশোর, প্রবন্ধ
শিশু-কিশোর, ধাঁধাঁ, বুদ্ধিবৃত্তিক খেলা
নজরুল সংগীত
দক্ষতা বৃদ্ধি
ক্রাইম অ্যাগেইনস্ট উইমেন
থ্রিলার, অ্যাডভেঞ্চার গল্প
ইলেক্ট্রনিক্স
কৃষি প্রযুক্তি, অর্থনীতি
ভূগোল
ব্যবসা-বানিজ্য, অর্থনীতি বিষয়ক প্রবন্ধ
ফ্যাশন, রূপচর্চা বিষয়ক বিবিধ বই
মুক্তিযুদ্ধ, ভাষা আন্দোলন বিষয়ক প্রবন্ধ
আত্ম-উন্নয়ন, মোটিভেশনাল, মেডিটেশন, ইংরেজি বই
এইচএসসি, আবশ্যিক বিষয়
স্বাধীনতা পূর্ব ইতিহাস
শিক্ষাবিদ
ইংরেজিতে কথ্য
পিএইচপি প্রোগ্রামিং
কলেজ, একাদশ শ্রেণি ভর্তি প্রস্তুতি
বিদেশী সামাজিক, রাজনৈতিক ম্যাগাজিন, মাসিক
রাজনৈতিক ইতিহাস
ইউরোপ ভ্রমণ
বইমেলা ২০১৪, বাংলাদেশ, মুক্তিযুদ্ধ
চিত্রনাট্য
প্রমাণ আইন
মেসোপটেমীয় সভ্যতা
কলা বিভাগে ভর্তি
ভর্তি, নিয়োগ সংগ্রহ
ব্যবসায় শিক্ষা ভর্তি প্রস্তুতি
মানবিক বিভাগ ভর্তি প্রস্তুতি
নবম, দশম এসএসসি, কমন সাবজেক্ট
অন্যদের কাজের প্রস্তুতি
দেওয়ানী কার্যবিধি, অনুশীলন আইন
পশ্চিমবঙ্গের ছড়া, কবিতা
বয়স যখন ১২-১৭, ইতিহাস, রাজনীতি
জীববিজ্ঞান
বিষয়ের উপর ভিত্তি করে অভিধান
অর্থনীতি বিভাগ, অনার্স ১ম বর্ষ
ব্যবসায়িক ব্যক্তিত্ব
প্রবন্ধ, অর্থনীতি, ব্যবসার উপর গবেষণা, পরিসংখ্যান
পাশ্চাত্য দর্শন
লোকশিল্প, সংস্কৃতি
ব্যবসা, অর্থনীতি বিষয়ক অনুবাদ, ইংরেজি বই
বাংলাদেশের অর্থনীতি, উন্নয়ন
শিশু-কিশোর, ছবি আঁকা, গান
বয়স যখন ১২-১৭, বিবিধ
অর্থনীতি বিভাগ, অনার্স ২য় বর্ষ
গণিত বিভাগ, অনার্স ১ম বর্ষ
হিসাববিজ্ঞান
বয়স যখন ১২-১৭, কবিতা
উদ্যোক্তা, ব্যবসায়িক ব্যক্তিত্ব
প্রোগ্রামিং বেসিক বই
দক্ষতা বৃদ্ধি, যোগাযোগ উন্নয়ন
পাইথন প্রোগ্রামিং
আর প্রোগ্রামিং
বিশ্ব অর্থনীতি
মার্ক্স
পরিবার-পরিকল্পনা, স্বাস্থ্য, নার্সিং নিয়োগ
লিখিত
সাধারণ জ্ঞান ম্যাগাজিন, বিশেষ সংস্করণ
ভাইভা
শিক্ষক, প্রভাষক নিয়োগ সহায়িকা
আধুনিক দর্শন
শিল্পীদের জীবন
ভাষার উপর প্রবন্ধ, গবেষণা, সমালোচনা
ফরাসি বিপ্লবের ইতিহাস
রকমারি কালেকশন
কুরআন সম্পর্কে
ধর্মীয় বই কালেকশন
রোযা, সিয়াম
পশ্চিমবঙ্গের বই, হিন্দু ধর্মীয় বই
আইটি বিষয়ক প্রবন্ধ, গবেষণা
প্রসেসিং
জীবনী, স্মৃতিচারণ, সাক্ষাৎকার
স্মৃতিচারণ, স্মারক, সাক্ষাৎকার
অনুবাদ, জীবনী, স্মৃতিচারণ, সাক্ষাৎকার
সাহিত্যিক, কবি, সংগীত ব্যক্তিত্ব
বাগান, ফুল, ফল চাষ
অ্যাডমিনিস্ট্রেটিভ ল
ইসলামিক স্টাডিজ টেক্সটবুক
আইন
ইসলাম, বিজ্ঞান
বাংলা ভাষা শিক্ষা
যখন ৮-১২, ধর্মীয় বই
অনুবাদিত গল্প
শিশু-কিশোর, কবিতা
বয়স যখন ১২-১৭, রেফারেন্স, আত্ম-উন্নয়নমূলক বই
কারিগরি শিক্ষা, হস্তশিল্প
এইচএসসি ১ম বর্ষ, মনোবিজ্ঞান পাঠ্য বই
এইচএসসি ২য় বর্ষ, মনোবিজ্ঞান পাঠ্য বই
এইচএসসি ২য় বর্ষ, রসায়ন পাঠ্য বই
সাহিত্য ম্যাগাজিন, ষান্মাাসিক
সমাজ, সভ্যতা কালেকশন
বিজ্ঞান বিষয়ক অনূদিত বই
পশ্চিমবঙ্গের বই, প্রবন্ধ কলাম সংগ্রহ, সংকলন
এইচএসসি ২য় বর্ষ, ভূগল পাঠ্য বই
এইচএসসি ২য় বর্ষ, পৌরনীতি পাঠ্য বই
পশ্চিমবঙ্গের বই, রহস্য, গোয়েন্দা উপন্যাস
মুক্তিযুদ্ধ, নারী মুক্তিযোদ্ধা, বীরাঙ্গনা
পশ্চিমবঙ্গের বই, ডায়েরি, চিঠিপত্র সংকলন
সামাজিক, রাজনৈতিক ম্যাগাজিন
চট্টগ্রাম
এইচএসসি ২য় বর্ষ, যুক্তিবিদ্যা পাঠ্য বই
এইচএসসি ২য় বর্ষ, হিসাববিজ্ঞান পাঠ্য বই
এইচএসসি ১ম বর্ষ, ভূগল পাঠ্য বই
এইচএসসি ১ম বর্ষ, যুক্তিবিদ্যা পাঠ্য বই
হার্ডওয়্যার, ট্রাবলশুটিং
ইন্টারনেট
ইসলামী বই, আত্ম-বিকাশ
প্রক্রিয়াকরণ
ভর্তি, নিয়োগ, প্রস্তুতি পরীক্ষা, বিবিধ
পশ্চিম বঙ্গের বই, স্বাস্থ্য বিষয়ক
কম্পিউটার, ইন্টারনেট, ফ্রিল্যান্সিং, আউটসোর্সিং কালেকশন
কুরআন শিক্ষা
বয়স যখন ৪-৮, গণিত, বিজ্ঞান, প্রযুক্তি
লালন সংগীত
সমগ্র, সংকলন কালেকশন
দার্শনিক
বিবিধ কালেকশন
গণিত, বিজ্ঞান, প্রযুক্তি কালেকশন
রকমারি নির্বাচিত বই, আত্ম-উন্নয়ন, মেডিটেশন
উপন্যাস, কবিতা, গল্প, নাটক কালেকশন
পর্দা বিধান
অনুবাদ বইয়ের কালেকশন
এথিক্যাল হ্যাকিং, সাইবার সিকিউরিটি
প্রবন্ধ কালেকশন
লেখা
ধর্মীয় বই সংগ্রহ
উপন্যাস কালেকশন
ব্যবসা, বিনিয়োগ, অর্থনীতি কালেকশন
ইতিহাস, ঐতিহ্য কালেকশন
গ্রাফিক্স ডিজাইন, মাল্টিমিডিয়া
গবেষণা পত্র
ডিটেকটিভ, ইন্টেলিজেন্স, সিক্রেট এজেন্সি
রাজনৈতিক বইয়ের কালেকশন
উত্তর বঙ্গ
সায়েন্স ফিকশন কালেকশন
ভাষা, অভিধান কালেকশন
বাংলাদেশ বিষয়াবলি
হাঁস, মুরগি, পাখি
কম্পিউটার প্রোগ্রামিং
শিশু-কিশোর, কমিকস, ছবির গল্প
যাকাত
চলচ্চিত্র ব্যক্তিত্ব
কন্সটিটিউশনাল ল
পাঠ্য বইয়ের কালেকশন
পূর্ব এশিয়ান ভাষা
নৈতিকতা, মূল্যবোধ, সুশাসন
ভূগোল বাংলাদেশ, বিশ্ব পরিবেশ, দুর্যোগ ব্যবস্থাপনা
আন্তর্জাতিক বিষয়াবলি
কম্পিউটার, তথ্য-প্রযুক্তি
বয়স যখন ৮-১২, সায়েন্স ফিকশন
মুক্তিযুদ্ধ কালেকশন
প্রাচ্য দর্শন
ভাষা, অভিধান সংগ্রহ
যখন ৮-১২, সীরাতে রাসুল সা
পশ্চিমবঙ্গের উপন্যাস
প্রফেশনাল,জার্নাল, রেফারেন্স, কালেকশন
ইসলামি অঞ্চল, শাসনব্যবস্থা, রাজনীতি
প্রাচীন ভারতের ইতিহাস
দর্শন কালেকশন
ওয়েব ডিজাইন, ডেভেলপমেন্ট
আরবি, উর্দু অভিধান
প্রত্নতাত্ত্বিক ইতিহাস
মুসলিম ইতিহাস
ভাষা ভিত্তিক অভিধান
আইন, বিচার কালেকশন
প্রতিবেদন সংকলন, সমগ্র
মধ্যপ্রাচ্যের ইতিহাস
আর্ট, ফটোগ্রাফি, ডিজাইন কালেকশন
বিজ্ঞান কিট
বইমেলা ২০১৯, ধর্মীয় বই
মনোবিজ্ঞান
প্রকৌশল, স্থাপত্যবিদ্যা
বৌদ্ধ ধর্মীয় ব্যক্তিত্ব
বাংলাদেশ বিষয়ক বইয়ের কালেকশন
পরিবার, স্বাস্থ্য পরিচর্যা কালেকশন
যন্ত্র, যন্ত্রসংগীত
বয়স যখন ৮-১২, ভাষা আন্দোলন, মুক্তিযুদ্ধ
শিশু-কিশোর, সায়েন্স ফিকশন
শিক্ষা, গবেষণা বিভাগ
ভাষার উপর ভিত্তি করে অভিধান
ইংরেজি বিভাগ, অনার্স ১ম বর্ষ
বিজ্ঞানী, গণিতবিদ
ভর্তি পরীক্ষার প্রস্তুতি
আইইএলটিএস
অনার্স
নবম, দশম বিজ্ঞান, পদার্থবিজ্ঞান পাঠ্য সহায়িকা
নবম, দশম বিজ্ঞান, রসায়ন পাঠ্য সহায়িকা
পশ্চিমবঙ্গের বই, ভৌতিক, অতিপ্রাকৃত গল্প

In [43]:
df_bn.loc[df_bn['categories_fixed'] == "ফ্যামিলি , পার্সোনাল লস", 'categories_fixed']

72237     ফ্যামিলি , পার্সোনাল লস
116571    ফ্যামিলি , পার্সোনাল লস
Name: categories_fixed, dtype: object

In [44]:
# নারী, শিশু ল
# ফ্যামিলি , পার্সোনাল লস
# অন্যরা
df_bn.loc[df_bn['categories_fixed'] == "ফ্যামিলি , পার্সোনাল লস", 'categories_fixed'] = "ফ্যামিলি, পার্সোনাল লস"

In [ ]:
# text = "ক্লাস ৯, ১০ এসএসসি, রসায়ন পাঠ সোহায়িকা, পাঠো সোহায়িকা"
text = "ক্লাস ৯-১০, বিজ্ঞান, ইংরেজি পাঠ সোহায়িকা"
text = re.sub(r'ক্লাস ৯, ১০', "ক্লাস ৯-১০,", text)
text = re.sub(r"(পাঠ\s)সোহায়িকা|(পাঠো\s)সোহায়িকা", "পাঠ্য সহায়িকা", text)
# text = re.sub(r"(পাঠো\s)সোহায়িকা", "পাঠ্য সহায়িকা", text)
print(text)

ক্লাস ৯-১০, বিজ্ঞান, ইংরেজি পাঠ্য সহায়িকা

In [46]:
df_bn.loc[:, 'categories_fixed'] = df_bn['categories_fixed'].apply(fix_more_categories_issue)

In [47]:
# no more
df_bn.loc[df_bn['categories_fixed'].str.contains("সোহায়িকা")]

Empty DataFrame
Columns: [book_id, title, author, publisher, publisher_name_english, categories, category_english, edition, isbn, summary, language, rating, n_ratings, n_reviews, price, offer_price, book_url, prod_img_link, availability, product_category, actual_rating, bangla_title, language_title, language_categories, categories_fixed]
Index: []

[0 rows x 25 columns]

In [48]:
# পাঠো
df_bn.loc[df_bn['categories_fixed'].str.contains("ক্লাস ৯, ১০")]

Empty DataFrame
Columns: [book_id, title, author, publisher, publisher_name_english, categories, category_english, edition, isbn, summary, language, rating, n_ratings, n_reviews, price, offer_price, book_url, prod_img_link, availability, product_category, actual_rating, bangla_title, language_title, language_categories, categories_fixed]
Index: []

[0 rows x 25 columns]

In [49]:
df_bn.to_csv("rokomari_books_only_bangla_v2.csv", index=False)

# Rough khata

In [ ]:
category_counts_df['cat_1'].value_counts()

cat_1
পশ্চিমবঙ্গের বই                     98
এইচএসসি ১ম বর্ষ                     42
এইচএসসি ২য় বর্ষ                     37
শিশু-কিশোর                          32
বয়স যখন ৮-১২                        28
                                    ..
ভর্তি, নিয়োগ ও প্রস্তুতি পরীক্ষা     1
বয়স যখন ৪-৮                          1
ইতিহাসে বাংলাদেশ                     1
এইচএসসি বিজ্ঞান বিভাগ                1
Engineering                          1
Name: count, Length: 163, dtype: int64

In [ ]:
category_1 = category_counts_df['cat_1'].value_counts()

In [ ]:
category_1[5:41]

cat_1
বয়স যখন ১২-১৭                      26
When 4-8                           14
বয়স যখন ৪-৮                       13
অনুবাদ                             12
মুক্তিযুদ্ধের ইতিহাস               11
বয়স যখন ৪-৮                        11
When 8-12                          10
ব্যবস্থাপনা বিভাগ                  10
উদ্ভিদবিজ্ঞান বিভাগ                 9
কওমি                                9
অর্থনীতি বিভাগ                      9
Qawmi                               9
নবম ও দশম (এসএসসি)                  9
ইতিহাস বিভাগ                        9
গণিত বিভাগ                          9
রাষ্ট্রবিজ্ঞান বিভাগ                9
ইসলাম শিক্ষা বিভাগ                  9
ফিন্যান্স বিভাগ                     9
এইচএসসি                             8
ভূগোল বিভাগ                         8
সমাজকর্ম বিভাগ                      8
পদার্থবিজ্ঞান বিভাগ                 8
সমাজবিজ্ঞান বিভাগ                   8
রসায়ন বিভাগ                         8
বয়স যখন ০-৪                        8
মার্কেটিং বিভাগ                     8
হিসাববিজ্ঞান বিভাগ                  8
When 0-4                            8
প্রাণীবিজ্ঞান বিভাগ                 8
ইলেকট্রিক্যাল ইঞ্জিনিয়ারিং          7
নবম ও দশম (বিজ্ঞান)                 7
বাংলা বিভাগ                         7
ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ     7
Foreign Language Books              6
মেকানিক্যাল ইঞ্জিনিয়ারিং            6
কম্পিউটার টেকনোলজি                  6
Name: count, dtype: int64

In [ ]:
category_counts_df.loc[category_counts_df['cat_1'] == "Foreign Language Books"]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
362,Foreign Language Books: Other Foreign Books,6,Foreign Language Books,Other Foreign Books,None,"[Foreign Language Books, Other Foreign Books]",2
558,Foreign Language Books: Islamic Books,2,Foreign Language Books,Islamic Books,None,"[Foreign Language Books, Islamic Books]",2
627,Foreign Language Books: Religious Books,1,Foreign Language Books,Religious Books,None,"[Foreign Language Books, Religious Books]",2
680,"Foreign Language Books: Mathematics, Science &...",1,Foreign Language Books,"Mathematics, Science & Technology",None,"[Foreign Language Books, Mathematics, Science...",2
683,Foreign Language Books: Self-help and meditation,1,Foreign Language Books,Self-help and meditation,None,"[Foreign Language Books, Self-help and medita...",2
719,"Foreign Language Books: Professional, Journal ...",1,Foreign Language Books,"Professional, Journal and Reference",None,"[Foreign Language Books, Professional, Journa...",2

In [ ]:
df_bn.loc[df_bn['categories'].str.contains(r'^Foreign Language Books:', regex=True)]

,author,categories,isbn,n_ratings,n_reviews,price,prod_img_link,publisher,rating,summary,title,language,summary_availability,language_author,language_categories
20496,মুনসি প্রেমচাঁদ,Foreign Language Books: Other Foreign Books,9798187335282,1,No Review,360,No image,Nai Sadi Book House,3.0,No summary,গোডান (হিন্দি),bn,No,bn,en
29632,এ আর কে শর্মা,Foreign Language Books: Other Foreign Books,9789383606115,1,No Review,180,https://ds.rokomari.store/rokomari110/ProductN...,Sri Sarada Book House (India),5.0,No summary,স্ট্রেন্থ ফার্স্ট গুডনেস নেক্সট,bn,No,bn,en
31080,পাওলো কোয়েলহো,Foreign Language Books: Other Foreign Books,9788183280921,No Ratings,No Reviews,405,No image,Wisdom Tree (India),0.0,No summary,জাহির (হিন্দি),bn,No,bn,en
33418,ড ভি আবদুর রহিম,"Foreign Language Books: Professional, Journal ...",No ISBN,2,No Review,7600,No image,U.K. Islamic Academy,3.0,No summary,এরাবিক কোর্স ফর ইংলিশ স্পিকিং স্টুডেন্টস (৩ভলি...,bn,No,bn,en
62024,বি কে শিবানী,Foreign Language Books: Other Foreign Books,9788182748576,1,No Review,351,https://ds.rokomari.store/rokomari110/ProductN...,Manjul Publishing House Pvt. Ltd (India),2.0,No summary,আসেম আনন্দ কি আর (হ্যাপিনেস আনলিমিটেড),bn,No,bn,en
62028,রোন্ডা বাইর্ন,Foreign Language Books: Other Foreign Books,9788183220941,1,No Review,718,https://ds.rokomari.store/rokomari110/ProductN...,Manjul Publishing House Pvt. Ltd (India),5.0,No summary,দ্যা সিক্রেট)(হিন্দি),bn,No,bn,en
66124,খান স্যার পাটনা,Foreign Language Books: Other Foreign Books,No ISBN,2,No Review,225,https://ds.rokomari.store/rokomari110/ProductN...,Kiran Prakashan,5.0,No summary,এনসিইআরটি ৩০০০ ফ্যাক্টস,bn,No,bn,en
76148,শায়খ সফিউর রহমান মোবারকপুরী,Foreign Language Books: Islamic Books,9786035000710,No Ratings,No Reviews,3960,No image,Darussalam (India),0.0,No summary,কালেকশন ফ্রম রিয়াদ উস সালেহীন,bn,No,bn,en
76156,দেভ আল কারদায়ী,Foreign Language Books: Religious Books,No ISBN,No Ratings,No Reviews,2800,No image,Darussalam (India),0.0,No summary,ডিকশনারি অব ইসলামিক টার্ম,bn,No,bn,en
94196,প্রসন্ত কুমার গিরি,"Foreign Language Books: Mathematics, Science &...",9789387162051,No Ratings,No Reviews,765,No image,Academic Publishers (Indian),0.0,No summary,ইন্ট্রোডাকশন টু স্ট্যাটিসটিক্স ইনক্লুডিং স্ট্য...,bn,No,bn,en
96467,ফরিদ বুক ডিপো ভারত সম্পাদক,Foreign Language Books: Islamic Books,No ISBN,No Ratings,No Reviews,1500,No image,Farid Book Depot (India),0.0,No summary,দ্য হলি কুরআন (উইথ কালার কোডেড ইংলিশ ট্রান্সলি...,bn,No,bn,en
96486,নেপোলিয়ন হিল,Foreign Language Books: Self-help and meditation,9788175993563,1,No Review,274,https://ds.rokomari.store/rokomari110/ProductN...,Fingerprint Publishing (India),5.0,One of the best inspirational books ever writt...,থিঙ্ক এন্ড গ্রো রিচ (হিন্দি),bn,Yes,bn,en

In [ ]:
print(category_1[category_1 == 1])

cat_1
কম্পিউটার সায়েন্স অ্যান্ড টেকনোলজি                      1
এইচএসসি মানবিক বিভাগ                                    1
Poem and Rhyme                                          1
Others                                                  1
Children & Teen Magazine                                1
বইমেলা ২০১৩                                             1
Self-Development                                        1
এনভায়রনমেন্টাল ইঞ্জিনিয়ারিং                             1
রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার, ও অ্যাডভেঞ্চার    1
Islamic Book                                            1
রকমারি নির্বাচিত বই                                     1
বিদেশী ফটোগ্রাফি ম্যাগাজিন                              1
History                                                 1
Self-Help, Motivational and Meditation                  1
HSC and Equivalent                                      1
টেস্ট পেপারস                                            1
Social and Political Magazine                           1
HSC Suggestion                                          1
Translated Books                                        1
Economics Department                                    1
When 12-17                                              1
Math Department                                         1
তত্ত্ব ও দর্শন                                          1
শিশু ও কিশোর                                            1
বিদেশী চলচ্চিত্র ও বিনোদন ম্যাগাজিন                     1
এসএসসি ও সমমান                                          1
ধর্মীয় বই                                               1
সংগীত                                                   1
ফ্যাশন ও রূপচর্চা                                       1
SSC and Equivalent                                      1
Exams Preparation                                       1
Islamic book                                            1
বিদেশি ভাষার বই                                         1
বাংলাদেশ                                                1
ভ্রমণ ও প্রবাস                                          1
সংগীত, চলচ্চিত্র ও বিনোদন                               1
কম্পিউটার ও টেকনোলজি ম্যাগাজিন                          1
HSC                                                     1
ভারতীয় উপমহাদেশের ইতিহাস                               1
পরিবেশ ও প্রকৃতি                                        1
বিদেশী অর্থনীতি, ব্যবসা ও বানিজ্য ম্যাগাজিন             1
মুক্তিযুদ্ধ                                             1
Story                                                   1
আত্ম-উন্নয়ন, মোটিভেশনাল ও মেডিটেশন                      1
Language & Dictionary                                   1
Professional, Journal & Reference                       1
ফটোগ্রাফি ম্যাগাজিন                                     1
জীবনী ও স্মৃতিচারণ                                      1
বিদেশী শিশু কিশোর ম্যাগাজিন                             1
Article                                                 1
ইংরেজি ও অনুবাদ                                         1
Medical                                                 1
ইতিহাস ও ঐতিহ্য                                         1
Literature Magazine                                     1
শাসনব্যবস্থা                                            1
ভর্তি, নিয়োগ ও প্রস্তুতি পরীক্ষা                        1
বয়স যখন ৪-৮                                             1
ইতিহাসে বাংলাদেশ                                        1
এইচএসসি বিজ্ঞান বিভাগ                                   1
Engineering                                             1
Name: count, dtype: int64

In [ ]:
category_counts_df['cat_2'].value_counts()

cat_2
 অনার্স ১ম বর্ষ                 24
 অনার্স ৩য় বর্ষ                 22
 অনার্স ২য় বর্ষ                 22
 অনার্স ৪র্থ বর্ষ               20
 ডিগ্রি ১ম বর্ষ                 19
                                ..
 ইন্টারভিউ                       1
 জীববিজ্ঞান পাঠ্য সহায়িকা       1
 মানবিক বিভাগ পাঠ্য সহায়িকা     1
 বিবিধ প্রসঙ্গ                   1
 ইংরেজি পাঠ্য সহায়িকা           1
Name: count, Length: 402, dtype: int64

In [ ]:
category_2 = category_counts_df['cat_2'].value_counts()
print(category_2[category_2 == 1])

cat_2
 Science Department Pattho Sohayika             1
 রান্না, স্বাস্থ্য, ফ্যাশন ও পরিবার বিষয়ক বই    1
আইসিটি পাঠ্য সহায়িকা                           1
 হিসাববিজ্ঞান পাঠ্য সহায়িকা                    1
 এসএসসি ও সমমান                                 1
                                               ..
 ইন্টারভিউ                                      1
 জীববিজ্ঞান পাঠ্য সহায়িকা                      1
 মানবিক বিভাগ পাঠ্য সহায়িকা                    1
 বিবিধ প্রসঙ্গ                                  1
 ইংরেজি পাঠ্য সহায়িকা                          1
Name: count, Length: 262, dtype: int64

In [ ]:
# save the modified dataframe

# df_bn.to_csv("rokomari_books_categories_corrected.csv", index=False)

In [ ]:
# df_bn.loc[df_bn['language_categories'] == 'en']

In [ ]:
# category_counts_df = pd.read_csv("/content/drive/MyDrive/Rokomari Recommendation Dataset/category_counts.csv")

In [ ]:
# def filter_cat(text):
#     return ':' in text

# category_counts_df = df_bn[df_bn['categories'].apply(filter_cat)]['categories'].value_counts().reset_index()

# another way to do this
category_counts_df = df_bn.loc[df_bn['categories'].str.contains(":"), 'categories'].value_counts().reset_index()

In [ ]:
# this is not necessary, also it's a good practice not to
# capitalize names

# category_counts_df.columns = ['Category', 'Count']
category_counts_df

                                            categories  count
0                             পশ্চিমবঙ্গের বই: প্রবন্ধ    924
1                         পশ্চিমবঙ্গের বই: বাংলা কবিতা    694
2                      অনুবাদ: আত্ম-উন্নয়ন ও মেডিটেশন    617
3    শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...    521
4                   পশ্চিমবঙ্গের বই: রচনাসমগ্র ও সংকলন    515
..                                                 ...    ...
800  নবম ও দশম (বিজ্ঞান): ধর্ম ও নৈতিক শিক্ষা পাঠ্য...      1
801                  ইঞ্জিনিয়ারিং: পরীক্ষার প্রস্তুতি      1
802                        মুক্তিযুদ্ধের ইতিহাস: বিবিধ      1
803  নবম ও দশম (ব্যবসায় শিক্ষা): বাংলাদেশ ও বিশ্ব প...      1
804  ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ: অনার্স ৪র্থ বর্ষ      1

[805 rows x 2 columns]

In [ ]:
# category_counts_df.to_csv('category_counts.csv', index=False)

In [ ]:
# df_bn['language_categories'] = df_bn['categories'].apply(detect_language)

In [ ]:
# df_bn['language_categories'].value_counts()

In [ ]:
df_bn.loc[df_bn['language_categories'].isin(["no", "sv", "pt", "vi", "cy"])]

,author,categories,isbn,n_ratings,n_reviews,price,prod_img_link,publisher,rating,summary,title,language,summary_availability,language_author,language_categories
1010,কবি মমতাজ রেনু,Poem Criticism,9843226488,No Ratings,No Reviews,430,https://ds.rokomari.store/rokomari110/ProductN...,Ahsania Books,0.00,"Ilhami(Inspired) Poetess Mumtaz Renu, a profou...",এঞ্জেল অন মাই শোল্ডারস্,bn,Yes,bn,pt
1012,কবি মমতাজ রেনু,Poem Criticism,No ISBN,No Ratings,No Reviews,1720,https://ds.rokomari.store/rokomari110/ProductN...,Ahsania Books,0.00,No summary,মেরি সুরাত তেরা আয়না,bn,No,bn,pt
9953,এসেনশিয়াল পাবলিকেশন সম্পাদক,TOEFL,No ISBN,7,7 Reviews,226,https://ds.rokomari.store/rokomari110/ProductN...,এসেনশিয়াল পাবলিকেশন,4.86,No summary,Cliffs Toefl Grand Review বাংলা ভার্সন,bn,No,bn,vi
9954,এসেনশিয়াল পাবলিকেশন সম্পাদক,TOEFL,No ISBN,No Ratings,No Reviews,226,https://ds.rokomari.store/rokomari110/ProductN...,এসেনশিয়াল পাবলিকেশন,0.00,CONTENTS,Cliffs Toefl Grand Review বাংলা ভার্সন,bn,Yes,bn,vi
11416,সোনিয়া পারভিন,Cyber Law,No ISBN,No Ratings,No Reviews,174,No image,Hasan Law Books,0.00,No summary,"সাইবার নিরাপত্তা আইন, ২০২৩",bn,No,bn,cy
14331,জয়কলি সম্পাদনা পরিষদ সম্পাদক,TOEFL,No ISBN,No Ratings,No Reviews,213,No image,জয়কলি পাবলিকেশন্স লিঃ,0.00,"সকল প্রশ্নের নির্ভুল উত্তর, সঠিক ব্যাখ্যা, প্র...",বারণ’স এন্ড ক্লিফস টোয়েফল - বাংলা অনুবাদ,bn,Yes,bn,vi
24467,মেজর শের মোহাম্মদ খান অবঃ অনুবাদক,Rhymes,978-984-97262-7-2,No Ratings,No Reviews,129,https://ds.rokomari.store/rokomari110/ProductN...,Raowa Publication,0.00,ছোটো সোনামনিদের ছড়ার বই। এই বইয়ের প্রতিটি ছড়া ...,ছােটােদর বাংলা ছড়া ও English Rhymes,bn,Yes,bn,cy
33028,বিচারপতি মোঃ আজিজুল হক,Cyber Law,9789849156499,No Ratings,No Reviews,898,https://ds.rokomari.store/rokomari110/ProductN...,Universal Book House,0.00,No summary,সাইবার ল এন্ড ক্রাইম,bn,No,bn,cy
33138,অ্যাডভোকেট জাহাঙ্গীর আলম সরকার,Cyber Law,978984892811,No Ratings,No Reviews,627,No image,Unique Law Book House,0.00,"১. সাইবার নিরাপত্তা আইন,২০২৩",সাইবার নিরাপত্তা আইনের ভাষ্য ও পর্নোগ্রাফি নিয়...,bn,Yes,bn,cy
34443,প্রফেসর মোঃ হাফিজুর রহমান,Honors,No ISBN,No Ratings,No Reviews,264,No image,Titas Publications,0.00,No summary,লিনিয়ার এলজাবরা - অনার্স ৩য় বর্ষ,bn,No,bn,no
35215,গ্রিন মিজানুর রহমান,Travelling Bangladesh,9789843495303,No Ratings,No Reviews,2819,https://ds.rokomari.store/rokomari110/ProductN...,Ten Ants Limited,0.00,"Green Mizanur Rahman, a scientist and renowned...",কক্সবাজার বাংলাদেশ ভ্রমণ মনোগ্রাফ,bn,Yes,bn,sv
55270,ওরাকল সম্পাদনা পর্ষদ সম্পাদক,College Level-Written,No ISBN,No Ratings,No Reviews,288,https://ds.rokomari.store/rokomari110/ProductN...,Oracle Publications,0.00,বেসরকারি শিক্ষক নিবন্ধন ও প্রত্যয়ন কর্তৃপক্ষ (...,ওরাকল প্রভাষক নিবন্ধন লিখিত - ইংলিশ,bn,Yes,bn,no
59256,ড মোঃ জাকারিয়া,E.N.T,9789848073766,1,No Review,308,https://ds.rokomari.store/rokomari110/ProductN...,মুক্তচিন্তা,5.00,"নাক, কান, গলা বা ইএনটি রোগে ভোগেন নাই, এমন মান...",নাক কান গলা রোগ ও চিকিৎসা,bn,Yes,bn,vi
60788,তহুরা খাতুন সম্পাদক,Rhymes,No ISBN,1,No Review,53,No image,Micros Digital Publishers,5.00,No summary,বেবি’স নার্সারী রাইমস্,bn,No,bn,cy
60789,তহুরা খাতুন,Rhymes,No ISBN,1,No Review,53,No image,Micros Digital Publishers,5.00,No summary,নার্সারী রেইমস্‌ - ০,bn,No,bn,cy
61850,তোফাজ্জল ইসলাম,Biology,9789843471888,No Ratings,No Reviews,275,https://ds.rokomari.store/rokomari110/ProductN...,Matrivasa Prokash,0.00,কোনো জীবের জিনোম হলো তার একটি কোষে উপস্থিত সমস...,জিনোম এডিটিং,bn,Yes,bn,cy
61933,জাহাঙ্গীর আলম ইমন সম্পাদক,TOEFL,9789843468703,24,15 Reviews,330,https://ds.rokomari.store/rokomari110/ProductN...,Masranga Publications,4.54,Grammar সম্পর্কিত বিশ্বখ্যাত অনলাইন জার্নালগুল...,ক্লিফস টোফেল ভিউ বাংলা ভার্সন,bn,Yes,bn,vi
61941,জাহাঙ্গীর আলম ইমন,TOEFL,No ISBN,No Ratings,No Reviews,300,https://ds.rokomari.store/rokomari110/ProductN...,Masranga Publications,0.00,BARRONS VIEW বইটি প্রকাশের উদ্দেশ্য ও প্রাথমিক...,ব্যারন্স টোফেল ভিউ বাংলা ভার্সন (হোয়াইটপ্রিন্ট),bn,Yes,bn,vi
70471,এ কে আজাদ ২,Rhymes,No ISBN,No,1 Review,133,https://ds.rokomari.store/rokomari110/ProductN...,International Book Supply,0.00,No summary,মাই বুক অব রেইমস,bn,No,bn,cy
72486,রাতুল রহমান,Travelling Bangladesh,9789849608806,No Ratings,No Reviews,2752,https://ds.rokomari.store/rokomari110/ProductN...,Facebangla,0.00,বাংলাদেশ জাতীয় গ্রন্থপঞ্জিতে বহুবার তালিকাভুক্...,কক্সবাজার বাংলাদেশ পর্যটন মনোগ্রাফ,bn,Yes,bn,sv
72506,এমআরজেড তুহিন,TOEFL,No ISBN,3,3 Reviews,160,https://ds.rokomari.store/rokomari110/ProductN...,English Publications,5.00,No summary,তুহিন‘স টোফেল গ্রামার ক্লিফ‘স অ্যান্ড ব্যারন‘স,bn,No,bn,vi
79069,মোঃ আতিকুর রহমান,Pathology,No ISBN,12,3 Reviews,629,https://ds.rokomari.store/rokomari110/ProductN...,Capital Book Center,3.92,আমার ক্ষুদ্র জ্ঞানে লিখা এ বইটি Laboratory Te...,এ হ্যান্ড বুক অন ক্যাপিটাল প্যাথলজী,bn,Yes,bn,cy
79101,আয়েশা খাতুন,When 0-4: Rhymes,No ISBN,No Ratings,No Reviews,71,No image,Care Books,0.00,No summary,নার্সারি রাইমস্-১ -,bn,No,bn,cy
91660,মুফতি মুহাম্মদ আব্দুল হান্নান,College Level-Written,No ISBN,1,No Review,799,https://ds.rokomari.store/rokomari110/ProductN...,Al-Baraka Library,5.00,শিক্ষা মন্ত্রণালয়ের অধীন NTRCA'র সিলেবাস আলোকে...,আরবি প্রভাষক নিবন্ধন গাইড - লিখিত পরীক্ষা,bn,Yes,bn,no
96000,এ কে চাকলাদার,Physiology,No ISBN,4,1 Review,718,https://ds.rokomari.store/rokomari110/ProductN...,এ বি পাবলিকেশন (ভারত),5.00,চিকিৎসাশাস্ত্র মূলত দাঁড়িয়ে আছে প্রাক্-নিদা...,অত্যাধুনিক ফিজিওলজী শিক্ষা (হিউম্যান ফিজিওলজী),bn,Yes,bn,cy

In [ ]:
df_bn.loc[df_bn['language_categories'].isin(["no", "sv", "pt", "vi", "cy"])].shape

(25, 15)

In [ ]:
category_counts_df = category_counts_df.join(
    category_counts_df['categories'].str.split(':', expand=True).rename(
        columns={0: 'cat_1', 1: 'cat_2', 2: 'cat_3'}
    )
)

In [ ]:
category_counts_df['categories_split'] = category_counts_df['categories'].str.split(":")

In [ ]:
category_counts_df

,categories,count,cat_1,cat_2,cat_3,categories_split
0,পশ্চিমবঙ্গের বই: প্রবন্ধ,924,পশ্চিমবঙ্গের বই,প্রবন্ধ,None,"[পশ্চিমবঙ্গের বই, প্রবন্ধ]"
1,পশ্চিমবঙ্গের বই: বাংলা কবিতা,694,পশ্চিমবঙ্গের বই,বাংলা কবিতা,None,"[পশ্চিমবঙ্গের বই, বাংলা কবিতা]"
2,অনুবাদ: আত্ম-উন্নয়ন ও মেডিটেশন,617,অনুবাদ,আত্ম-উন্নয়ন ও মেডিটেশন,None,"[অনুবাদ, আত্ম-উন্নয়ন ও মেডিটেশন]"
3,"শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...",521,শিশু-কিশোর,"রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও অ্যাডভেঞ্চার",None,"[শিশু-কিশোর, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ..."
4,পশ্চিমবঙ্গের বই: রচনাসমগ্র ও সংকলন,515,পশ্চিমবঙ্গের বই,রচনাসমগ্র ও সংকলন,None,"[পশ্চিমবঙ্গের বই, রচনাসমগ্র ও সংকলন]"
...,...,...,...,...,...,...
800,নবম ও দশম (বিজ্ঞান): ধর্ম ও নৈতিক শিক্ষা পাঠ্য...,1,নবম ও দশম (বিজ্ঞান),ধর্ম ও নৈতিক শিক্ষা পাঠ্য সহায়িকা,None,"[নবম ও দশম (বিজ্ঞান), ধর্ম ও নৈতিক শিক্ষা পাঠ..."
801,ইঞ্জিনিয়ারিং: পরীক্ষার প্রস্তুতি,1,ইঞ্জিনিয়ারিং,পরীক্ষার প্রস্তুতি,None,"[ইঞ্জিনিয়ারিং, পরীক্ষার প্রস্তুতি]"
802,মুক্তিযুদ্ধের ইতিহাস: বিবিধ,1,মুক্তিযুদ্ধের ইতিহাস,বিবিধ,None,"[মুক্তিযুদ্ধের ইতিহাস, বিবিধ]"
803,নবম ও দশম (ব্যবসায় শিক্ষা): বাংলাদেশ ও বিশ্ব প...,1,নবম ও দশম (ব্যবসায় শিক্ষা),বাংলাদেশ ও বিশ্ব পরিচয় পাঠ্য সহায়িকা,None,"[নবম ও দশম (ব্যবসায় শিক্ষা), বাংলাদেশ ও বিশ্ব..."
804,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ: অনার্স ৪র্থ বর্ষ,1,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ,অনার্স ৪র্থ বর্ষ,None,"[ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ, অনার্স ৪র্থ..."

In [ ]:
category_counts_df['category_length'] = category_counts_df['categories_split'].apply(lambda x: len(x))

In [ ]:
category_counts_df.head()

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
0,পশ্চিমবঙ্গের বই: প্রবন্ধ,924,পশ্চিমবঙ্গের বই,প্রবন্ধ,None,"[পশ্চিমবঙ্গের বই, প্রবন্ধ]",2
1,পশ্চিমবঙ্গের বই: বাংলা কবিতা,694,পশ্চিমবঙ্গের বই,বাংলা কবিতা,None,"[পশ্চিমবঙ্গের বই, বাংলা কবিতা]",2
2,অনুবাদ: আত্ম-উন্নয়ন ও মেডিটেশন,617,অনুবাদ,আত্ম-উন্নয়ন ও মেডিটেশন,None,"[অনুবাদ, আত্ম-উন্নয়ন ও মেডিটেশন]",2
3,"শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...",521,শিশু-কিশোর,"রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও অ্যাডভেঞ্চার",None,"[শিশু-কিশোর, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ...",2
4,পশ্চিমবঙ্গের বই: রচনাসমগ্র ও সংকলন,515,পশ্চিমবঙ্গের বই,রচনাসমগ্র ও সংকলন,None,"[পশ্চিমবঙ্গের বই, রচনাসমগ্র ও সংকলন]",2

In [ ]:
category_counts_df['category_length'].value_counts()

category_length
2    802
3      3
Name: count, dtype: int64

In [ ]:
# to get the values where cat_3 == None

category_counts_df.loc[(category_counts_df['cat_3'].isna())]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
0,পশ্চিমবঙ্গের বই: প্রবন্ধ,924,পশ্চিমবঙ্গের বই,প্রবন্ধ,None,"[পশ্চিমবঙ্গের বই, প্রবন্ধ]",2
1,পশ্চিমবঙ্গের বই: বাংলা কবিতা,694,পশ্চিমবঙ্গের বই,বাংলা কবিতা,None,"[পশ্চিমবঙ্গের বই, বাংলা কবিতা]",2
2,অনুবাদ: আত্ম-উন্নয়ন ও মেডিটেশন,617,অনুবাদ,আত্ম-উন্নয়ন ও মেডিটেশন,None,"[অনুবাদ, আত্ম-উন্নয়ন ও মেডিটেশন]",2
3,"শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...",521,শিশু-কিশোর,"রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও অ্যাডভেঞ্চার",None,"[শিশু-কিশোর, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ...",2
4,পশ্চিমবঙ্গের বই: রচনাসমগ্র ও সংকলন,515,পশ্চিমবঙ্গের বই,রচনাসমগ্র ও সংকলন,None,"[পশ্চিমবঙ্গের বই, রচনাসমগ্র ও সংকলন]",2
...,...,...,...,...,...,...,...
800,নবম ও দশম (বিজ্ঞান): ধর্ম ও নৈতিক শিক্ষা পাঠ্য...,1,নবম ও দশম (বিজ্ঞান),ধর্ম ও নৈতিক শিক্ষা পাঠ্য সহায়িকা,None,"[নবম ও দশম (বিজ্ঞান), ধর্ম ও নৈতিক শিক্ষা পাঠ...",2
801,ইঞ্জিনিয়ারিং: পরীক্ষার প্রস্তুতি,1,ইঞ্জিনিয়ারিং,পরীক্ষার প্রস্তুতি,None,"[ইঞ্জিনিয়ারিং, পরীক্ষার প্রস্তুতি]",2
802,মুক্তিযুদ্ধের ইতিহাস: বিবিধ,1,মুক্তিযুদ্ধের ইতিহাস,বিবিধ,None,"[মুক্তিযুদ্ধের ইতিহাস, বিবিধ]",2
803,নবম ও দশম (ব্যবসায় শিক্ষা): বাংলাদেশ ও বিশ্ব প...,1,নবম ও দশম (ব্যবসায় শিক্ষা),বাংলাদেশ ও বিশ্ব পরিচয় পাঠ্য সহায়িকা,None,"[নবম ও দশম (ব্যবসায় শিক্ষা), বাংলাদেশ ও বিশ্ব...",2
804,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ: অনার্স ৪র্থ বর্ষ,1,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ,অনার্স ৪র্থ বর্ষ,None,"[ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ, অনার্স ৪র্থ...",2

`Fill the `None` values with empty ("") string`

In [ ]:
category_counts_df.loc[:, 'cat_3'].fillna("", inplace=True)

In [ ]:
category_counts_df.head()

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
0,পশ্চিমবঙ্গের বই: প্রবন্ধ,924,পশ্চিমবঙ্গের বই,প্রবন্ধ,,"[পশ্চিমবঙ্গের বই, প্রবন্ধ]",2
1,পশ্চিমবঙ্গের বই: বাংলা কবিতা,694,পশ্চিমবঙ্গের বই,বাংলা কবিতা,,"[পশ্চিমবঙ্গের বই, বাংলা কবিতা]",2
2,অনুবাদ: আত্ম-উন্নয়ন ও মেডিটেশন,617,অনুবাদ,আত্ম-উন্নয়ন ও মেডিটেশন,,"[অনুবাদ, আত্ম-উন্নয়ন ও মেডিটেশন]",2
3,"শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...",521,শিশু-কিশোর,"রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও অ্যাডভেঞ্চার",,"[শিশু-কিশোর, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ...",2
4,পশ্চিমবঙ্গের বই: রচনাসমগ্র ও সংকলন,515,পশ্চিমবঙ্গের বই,রচনাসমগ্র ও সংকলন,,"[পশ্চিমবঙ্গের বই, রচনাসমগ্র ও সংকলন]",2

In [ ]:
category_counts_df.tail()

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
800,নবম ও দশম (বিজ্ঞান): ধর্ম ও নৈতিক শিক্ষা পাঠ্য...,1,নবম ও দশম (বিজ্ঞান),ধর্ম ও নৈতিক শিক্ষা পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), ধর্ম ও নৈতিক শিক্ষা পাঠ...",2
801,ইঞ্জিনিয়ারিং: পরীক্ষার প্রস্তুতি,1,ইঞ্জিনিয়ারিং,পরীক্ষার প্রস্তুতি,,"[ইঞ্জিনিয়ারিং, পরীক্ষার প্রস্তুতি]",2
802,মুক্তিযুদ্ধের ইতিহাস: বিবিধ,1,মুক্তিযুদ্ধের ইতিহাস,বিবিধ,,"[মুক্তিযুদ্ধের ইতিহাস, বিবিধ]",2
803,নবম ও দশম (ব্যবসায় শিক্ষা): বাংলাদেশ ও বিশ্ব প...,1,নবম ও দশম (ব্যবসায় শিক্ষা),বাংলাদেশ ও বিশ্ব পরিচয় পাঠ্য সহায়িকা,,"[নবম ও দশম (ব্যবসায় শিক্ষা), বাংলাদেশ ও বিশ্ব...",2
804,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ: অনার্স ৪র্থ বর্ষ,1,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ,অনার্স ৪র্থ বর্ষ,,"[ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ, অনার্স ৪র্থ...",2

In [ ]:
category_counts_df.loc[category_counts_df['cat_1'] == "শিশু-কিশোর"]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
3,"শিশু-কিশোর: রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও ...",521,শিশু-কিশোর,"রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ও অ্যাডভেঞ্চার",,"[শিশু-কিশোর, রহস্য, গোয়েন্দা, ভৌতিক, থ্রিলার ...",2
22,শিশু-কিশোর: বিবিধ,212,শিশু-কিশোর,বিবিধ,,"[শিশু-কিশোর, বিবিধ]",2
32,শিশু-কিশোর: বিখ্যাত ব্যক্তি ও জীবনী,148,শিশু-কিশোর,বিখ্যাত ব্যক্তি ও জীবনী,,"[শিশু-কিশোর, বিখ্যাত ব্যক্তি ও জীবনী]",2
45,"শিশু-কিশোর: রূপকথা, উপকথা ও লোককাহিনী",107,শিশু-কিশোর,"রূপকথা, উপকথা ও লোককাহিনী",,"[শিশু-কিশোর, রূপকথা, উপকথা ও লোককাহিনী]",2
50,শিশু-কিশোর: রেফারেন্স ও আত্মউন্নয়নমূলক বই,95,শিশু-কিশোর,রেফারেন্স ও আত্মউন্নয়নমূলক বই,,"[শিশু-কিশোর, রেফারেন্স ও আত্মউন্নয়নমূলক বই]",2
67,শিশু-কিশোর: রচনাসমগ্র/সংকলন,70,শিশু-কিশোর,রচনাসমগ্র/সংকলন,,"[শিশু-কিশোর, রচনাসমগ্র/সংকলন]",2
68,শিশু-কিশোর: ছবি আঁকা ও গান,69,শিশু-কিশোর,ছবি আঁকা ও গান,,"[শিশু-কিশোর, ছবি আঁকা ও গান]",2
69,শিশু-কিশোর: সাধারণ জ্ঞান,67,শিশু-কিশোর,সাধারণ জ্ঞান,,"[শিশু-কিশোর, সাধারণ জ্ঞান]",2
79,"শিশু-কিশোর: গণিত, বিজ্ঞান ও প্রযুক্তি",57,শিশু-কিশোর,"গণিত, বিজ্ঞান ও প্রযুক্তি",,"[শিশু-কিশোর, গণিত, বিজ্ঞান ও প্রযুক্তি]",2
84,শিশু-কিশোর: ভাষা আন্দোলন ও মুক্তিযুদ্ধ,54,শিশু-কিশোর,ভাষা আন্দোলন ও মুক্তিযুদ্ধ,,"[শিশু-কিশোর, ভাষা আন্দোলন ও মুক্তিযুদ্ধ]",2
97,শিশু-কিশোর: ছড়া,46,শিশু-কিশোর,ছড়া,,"[শিশু-কিশোর, ছড়া]",2
99,শিশু-কিশোর: গল্প,45,শিশু-কিশোর,গল্প,,"[শিশু-কিশোর, গল্প]",2
102,শিশু-কিশোর: ধর্মীয় বই,42,শিশু-কিশোর,ধর্মীয় বই,,"[শিশু-কিশোর, ধর্মীয় বই]",2
124,শিশু-কিশোর: কবিতা,33,শিশু-কিশোর,কবিতা,,"[শিশু-কিশোর, কবিতা]",2
125,শিশু-কিশোর: রম্য ও ব্যঙ্গ রচনা,33,শিশু-কিশোর,রম্য ও ব্যঙ্গ রচনা,,"[শিশু-কিশোর, রম্য ও ব্যঙ্গ রচনা]",2
127,শিশু-কিশোর: ইতিহাস ও রাজনীতি,32,শিশু-কিশোর,ইতিহাস ও রাজনীতি,,"[শিশু-কিশোর, ইতিহাস ও রাজনীতি]",2
138,শিশু-কিশোর: ভৌতিক,28,শিশু-কিশোর,ভৌতিক,,"[শিশু-কিশোর, ভৌতিক]",2
190,শিশু-কিশোর: প্রবন্ধ,20,শিশু-কিশোর,প্রবন্ধ,,"[শিশু-কিশোর, প্রবন্ধ]",2
204,শিশু-কিশোর: প্রাণী ও জীবজগৎ,19,শিশু-কিশোর,প্রাণী ও জীবজগৎ,,"[শিশু-কিশোর, প্রাণী ও জীবজগৎ]",2
239,শিশু-কিশোর: কম্পিউটার ও ইন্টারনেট,14,শিশু-কিশোর,কম্পিউটার ও ইন্টারনেট,,"[শিশু-কিশোর, কম্পিউটার ও ইন্টারনেট]",2
281,শিশু-কিশোর: পরিবেশ ও প্রকৃতি,11,শিশু-কিশোর,পরিবেশ ও প্রকৃতি,,"[শিশু-কিশোর, পরিবেশ ও প্রকৃতি]",2
297,শিশু-কিশোর: ধাঁধাঁ ও বুদ্ধিবৃত্তিক খেলা,9,শিশু-কিশোর,ধাঁধাঁ ও বুদ্ধিবৃত্তিক খেলা,,"[শিশু-কিশোর, ধাঁধাঁ ও বুদ্ধিবৃত্তিক খেলা]",2
352,শিশু-কিশোর: উপন্যাস,6,শিশু-কিশোর,উপন্যাস,,"[শিশু-কিশোর, উপন্যাস]",2
366,শিশু-কিশোর: সায়েন্স ফিকশন,6,শিশু-কিশোর,সায়েন্স ফিকশন,,"[শিশু-কিশোর, সায়েন্স ফিকশন]",2
407,"শিশু-কিশোর: রহস্য, গোয়েন্দা, থ্রিলার ও অ্যাডভ...",5,শিশু-কিশোর,"রহস্য, গোয়েন্দা, থ্রিলার ও অ্যাডভেঞ্চার",,"[শিশু-কিশোর, রহস্য, গোয়েন্দা, থ্রিলার ও অ্যা...",2
411,শিশু-কিশোর: কমিকস ও ছবির গল্প,5,শিশু-কিশোর,কমিকস ও ছবির গল্প,,"[শিশু-কিশোর, কমিকস ও ছবির গল্প]",2
425,শিশু-কিশোর: নাটক,4,শিশু-কিশোর,নাটক,,"[শিশু-কিশোর, নাটক]",2
478,শিশু-কিশোর: গান ও নাটক,3,শিশু-কিশোর,গান ও নাটক,,"[শিশু-কিশোর, গান ও নাটক]",2
554,শিশু-কিশোর: কথাসাহিত্য ও সাহিত্য,2,শিশু-কিশোর,কথাসাহিত্য ও সাহিত্য,,"[শিশু-কিশোর, কথাসাহিত্য ও সাহিত্য]",2
556,শিশু-কিশোর: ছড়া ও কবিতা,2,শিশু-কিশোর,ছড়া ও কবিতা,,"[শিশু-কিশোর, ছড়া ও কবিতা]",2
574,শিশু-কিশোর: গান,2,শিশু-কিশোর,গান,,"[শিশু-কিশোর, গান]",2
584,শিশু-কিশোর: প্রাথমিক শিক্ষা,2,শিশু-কিশোর,প্রাথমিক শিক্ষা,,"[শিশু-কিশোর, প্রাথমিক শিক্ষা]",2

In [ ]:
category_counts_df.loc[category_counts_df['cat_1'] == "অনুবাদ"]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
2,অনুবাদ: আত্ম-উন্নয়ন ও মেডিটেশন,617,অনুবাদ,আত্ম-উন্নয়ন ও মেডিটেশন,,"[অনুবাদ, আত্ম-উন্নয়ন ও মেডিটেশন]",2
498,"অনুবাদ: জীবনী, স্মৃতিচারণ ও সাক্ষাৎকার",3,অনুবাদ,"জীবনী, স্মৃতিচারণ ও সাক্ষাৎকার",,"[অনুবাদ, জীবনী, স্মৃতিচারণ ও সাক্ষাৎকার]",2
567,অনুবাদ: প্রবন্ধ,2,অনুবাদ,প্রবন্ধ,,"[অনুবাদ, প্রবন্ধ]",2
593,অনুবাদ: শিশু-কিশোর,2,অনুবাদ,শিশু-কিশোর,,"[অনুবাদ, শিশু-কিশোর]",2
629,অনুবাদ: কমিকস ও নকশা,1,অনুবাদ,কমিকস ও নকশা,,"[অনুবাদ, কমিকস ও নকশা]",2
646,অনুবাদ: ইসলাম,1,অনুবাদ,ইসলাম,,"[অনুবাদ, ইসলাম]",2
657,অনুবাদ: বিবিধ ধর্মীয় বই,1,অনুবাদ,বিবিধ ধর্মীয় বই,,"[অনুবাদ, বিবিধ ধর্মীয় বই]",2
660,অনুবাদ: পৌরাণিক কাহিনী,1,অনুবাদ,পৌরাণিক কাহিনী,,"[অনুবাদ, পৌরাণিক কাহিনী]",2
686,"অনুবাদ: ব্যবসা, বিনিয়োগ ও অর্থনীতি",1,অনুবাদ,"ব্যবসা, বিনিয়োগ ও অর্থনীতি",,"[অনুবাদ, ব্যবসা, বিনিয়োগ ও অর্থনীতি]",2
687,"অনুবাদ:রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার, ও...",1,অনুবাদ,"রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার, ও অ্যাডভ...",,"[অনুবাদ, রহস্য, গোয়েন্দা, ভৌতিক, মিথ, থ্রিলার,...",2
720,অনুবাদ: উপন্যাস,1,অনুবাদ,উপন্যাস,,"[অনুবাদ, উপন্যাস]",2
765,অনুবাদ: ইতিহাস ও ঐতিহ্য,1,অনুবাদ,ইতিহাস ও ঐতিহ্য,,"[অনুবাদ, ইতিহাস ও ঐতিহ্য]",2

In [ ]:
category_counts_df.loc[category_counts_df['cat_2'].str.contains("পাঠ্য সহায়িকা", regex=True)]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
100,এইচএসসি ১ম বর্ষ: গণিত পাঠ্য সহায়িকা,43,এইচএসসি ১ম বর্ষ,গণিত পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, গণিত পাঠ্য সহায়িকা]",2
111,এইচএসসি ১ম বর্ষ: পদার্থবিজ্ঞান পাঠ্য সহায়িকা,38,এইচএসসি ১ম বর্ষ,পদার্থবিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, পদার্থবিজ্ঞান পাঠ্য সহায়িকা]",2
123,এইচএসসি ১ম বর্ষ: রসায়ন পাঠ্য সহায়িকা,33,এইচএসসি ১ম বর্ষ,রসায়ন পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, রসায়ন পাঠ্য সহায়িকা]",2
180,এইচএসসি ১ম বর্ষ: জীববিজ্ঞান পাঠ্য সহায়িকা,21,এইচএসসি ১ম বর্ষ,জীববিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, জীববিজ্ঞান পাঠ্য সহায়িকা]",2
230,এইচএসসি ২য় বর্ষ: পদার্থবিজ্ঞান পাঠ্য সহায়িকা,16,এইচএসসি ২য় বর্ষ,পদার্থবিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, পদার্থবিজ্ঞান পাঠ্য সহায়িকা]",2
284,এইচএসসি ২য় বর্ষ: রসায়ন পাঠ্য সহায়িকা,11,এইচএসসি ২য় বর্ষ,রসায়ন পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, রসায়ন পাঠ্য সহায়িকা]",2
313,এইচএসসি ২য় বর্ষ: গণিত পাঠ্য সহায়িকা,9,এইচএসসি ২য় বর্ষ,গণিত পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, গণিত পাঠ্য সহায়িকা]",2
381,এইচএসসি ২য় বর্ষ: জীববিজ্ঞান পাঠ্য সহায়িকা,6,এইচএসসি ২য় বর্ষ,জীববিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, জীববিজ্ঞান পাঠ্য সহায়িকা]",2
389,এইচএসসি ১ম বর্ষ: তথ্য ও যোগাযোগ প্রযুক্তি পাঠ্...,5,এইচএসসি ১ম বর্ষ,তথ্য ও যোগাযোগ প্রযুক্তি পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, তথ্য ও যোগাযোগ প্রযুক্তি পা...",2
455,এইচএসসি ২য় বর্ষ: সমাজবিজ্ঞান/সমাজকর্ম পাঠ্য সহ...,4,এইচএসসি ২য় বর্ষ,সমাজবিজ্ঞান/সমাজকর্ম পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, সমাজবিজ্ঞান/সমাজকর্ম পাঠ্য ...",2
464,এইচএসসি ১ম বর্ষ: ব্যবসায় সংগঠন ও ব্যবস্থাপনা প...,3,এইচএসসি ১ম বর্ষ,ব্যবসায় সংগঠন ও ব্যবস্থাপনা পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, ব্যবসায় সংগঠন ও ব্যবস্থাপনা...",2
466,এইচএসসি ২য় বর্ষ: ইসলামের ইতিহাস পাঠ্য সহায়িকা,3,এইচএসসি ২য় বর্ষ,ইসলামের ইতিহাস পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, ইসলামের ইতিহাস পাঠ্য সহায়িকা]",2
467,"এইচএসসি ১ম বর্ষ: ফিন্যান্স, ব্যাংকিং ও বিমা পা...",3,এইচএসসি ১ম বর্ষ,"ফিন্যান্স, ব্যাংকিং ও বিমা পাঠ্য সহায়িকা",,"[এইচএসসি ১ম বর্ষ, ফিন্যান্স, ব্যাংকিং ও বিমা ...",2
473,এইচএসসি ১ম বর্ষ: যুক্তিবিদ্যা পাঠ্য সহায়িকা,3,এইচএসসি ১ম বর্ষ,যুক্তিবিদ্যা পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, যুক্তিবিদ্যা পাঠ্য সহায়িকা]",2
481,এইচএসসি ১ম বর্ষ: সমাজবিজ্ঞান/সমাজকর্ম পাঠ্য সহ...,3,এইচএসসি ১ম বর্ষ,সমাজবিজ্ঞান/সমাজকর্ম পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, সমাজবিজ্ঞান/সমাজকর্ম পাঠ্য ...",2
540,এইচএসসি ১ম বর্ষ: অর্থনীতি পাঠ্য সহায়িকা,2,এইচএসসি ১ম বর্ষ,অর্থনীতি পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, অর্থনীতি পাঠ্য সহায়িকা]",2
542,এইচএসসি ১ম বর্ষ: পৌরনীতি পাঠ্য সহায়িকা,2,এইচএসসি ১ম বর্ষ,পৌরনীতি পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, পৌরনীতি পাঠ্য সহায়িকা]",2
561,এইচএসসি ২য় বর্ষ: ইতিহাস পাঠ্য সহায়িকা,2,এইচএসসি ২য় বর্ষ,ইতিহাস পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, ইতিহাস পাঠ্য সহায়িকা]",2
564,এইচএসসি ১ম বর্ষ: হিসাববিজ্ঞান পাঠ্য সহায়িকা,2,এইচএসসি ১ম বর্ষ,হিসাববিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, হিসাববিজ্ঞান পাঠ্য সহায়িকা]",2
565,এইচএসসি ১ম বর্ষ: মনোবিজ্ঞান পাঠ্য সহায়িকা,2,এইচএসসি ১ম বর্ষ,মনোবিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, মনোবিজ্ঞান পাঠ্য সহায়িকা]",2
573,এইচএসসি ২য় বর্ষ: ইসলাম শিক্ষা পাঠ্য সহায়িকা,2,এইচএসসি ২য় বর্ষ,ইসলাম শিক্ষা পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, ইসলাম শিক্ষা পাঠ্য সহায়িকা]",2
590,এইচএসসি ১ম বর্ষ: ভূগল পাঠ্য সহায়িকা,2,এইচএসসি ১ম বর্ষ,ভূগল পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, ভূগল পাঠ্য সহায়িকা]",2
598,এইচএসসি ২য় বর্ষ: পৌরনীতি পাঠ্য সহায়িকা,2,এইচএসসি ২য় বর্ষ,পৌরনীতি পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, পৌরনীতি পাঠ্য সহায়িকা]",2
601,এইচএসসি ২য় বর্ষ: হিসাববিজ্ঞান পাঠ্য সহায়িকা,2,এইচএসসি ২য় বর্ষ,হিসাববিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, হিসাববিজ্ঞান পাঠ্য সহায়িকা]",2
625,এইচএসসি ১ম বর্ষ: বাংলা পাঠ্য সহায়িকা,1,এইচএসসি ১ম বর্ষ,বাংলা পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, বাংলা পাঠ্য সহায়িকা]",2
635,এইচএসসি ২য় বর্ষ: পরিসংখ্যান পাঠ্য সহায়িকা,1,এইচএসসি ২য় বর্ষ,পরিসংখ্যান পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, পরিসংখ্যান পাঠ্য সহায়িকা]",2
649,এইচএসসি ২য় বর্ষ: যুক্তিবিদ্যা পাঠ্য সহায়িকা,1,এইচএসসি ২য় বর্ষ,যুক্তিবিদ্যা পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, যুক্তিবিদ্যা পাঠ্য সহায়িকা]",2
701,এইচএসসি ২য় বর্ষ: ব্যবসায় সংগঠন ও ব্যবস্থাপনা প...,1,এইচএসসি ২য় বর্ষ,ব্যবসায় সংগঠন ও ব্যবস্থাপনা পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, ব্যবসায় সংগঠন ও ব্যবস্থাপনা...",2
703,"এইচএসসি ২য় বর্ষ: ফিন্যান্স, ব্যাংকিং ও বিমা পা...",1,এইচএসসি ২য় বর্ষ,"ফিন্যান্স, ব্যাংকিং ও বিমা পাঠ্য সহায়িকা",,"[এইচএসসি ২য় বর্ষ, ফিন্যান্স, ব্যাংকিং ও বিমা ...",2
780,এইচএসসি ১ম বর্ষ: ইতিহাস পাঠ্য সহায়িকা,1,এইচএসসি ১ম বর্ষ,ইতিহাস পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, ইতিহাস পাঠ্য সহায়িকা]",2
781,এইচএসসি ২য় বর্ষ: গার্হস্থ্য বিজ্ঞান পাঠ্য সহায়িকা,1,এইচএসসি ২য় বর্ষ,গার্হস্থ্য বিজ্ঞান পাঠ্য সহায়িকা,,"[এইচএসসি ২য় বর্ষ, গার্হস্থ্য বিজ্ঞান পাঠ্য সহ...",2
782,এইচএসসি ১ম বর্ষ: ইসলাম শিক্ষা পাঠ্য সহায়িকা,1,এইচএসসি ১ম বর্ষ,ইসলাম শিক্ষা পাঠ্য সহায়িকা,,"[এইচএসসি ১ম বর্ষ, ইসলাম শিক্ষা পাঠ্য সহায়িকা]",2
800,নবম ও দশম (বিজ্ঞান): ধর্ম ও নৈতিক শিক্ষা পাঠ্য...,1,নবম ও দশম (বিজ্ঞান),ধর্ম ও নৈতিক শিক্ষা পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), ধর্ম ও নৈতিক শিক্ষা পাঠ...",2

In [ ]:
category_counts_df.loc[category_counts_df['cat_2'].str.contains("অনার্স", regex=True)]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
87,রাষ্ট্রবিজ্ঞান বিভাগ: অনার্স ১ম বর্ষ,52,রাষ্ট্রবিজ্ঞান বিভাগ,অনার্স ১ম বর্ষ,,"[রাষ্ট্রবিজ্ঞান বিভাগ, অনার্স ১ম বর্ষ]",2
104,ভূগোল বিভাগ: অনার্স ১ম বর্ষ,41,ভূগোল বিভাগ,অনার্স ১ম বর্ষ,,"[ভূগোল বিভাগ, অনার্স ১ম বর্ষ]",2
110,রাষ্ট্রবিজ্ঞান বিভাগ: অনার্স ৪র্থ বর্ষ,38,রাষ্ট্রবিজ্ঞান বিভাগ,অনার্স ৪র্থ বর্ষ,,"[রাষ্ট্রবিজ্ঞান বিভাগ, অনার্স ৪র্থ বর্ষ]",2
117,ইতিহাস বিভাগ: অনার্স ১ম বর্ষ,36,ইতিহাস বিভাগ,অনার্স ১ম বর্ষ,,"[ইতিহাস বিভাগ, অনার্স ১ম বর্ষ]",2
118,রাষ্ট্রবিজ্ঞান বিভাগ: অনার্স ২য় বর্ষ,35,রাষ্ট্রবিজ্ঞান বিভাগ,অনার্স ২য় বর্ষ,,"[রাষ্ট্রবিজ্ঞান বিভাগ, অনার্স ২য় বর্ষ]",2
...,...,...,...,...,...,...,...
753,অর্থনীতি বিভাগ: অনার্স ৩য় বর্ষ,1,অর্থনীতি বিভাগ,অনার্স ৩য় বর্ষ,,"[অর্থনীতি বিভাগ, অনার্স ৩য় বর্ষ]",2
755,পরিসংখ্যান বিভাগ: অনার্স ২য় বর্ষ,1,পরিসংখ্যান বিভাগ,অনার্স ২য় বর্ষ,,"[পরিসংখ্যান বিভাগ, অনার্স ২য় বর্ষ]",2
767,লোক প্রশাসন বিভাগ: অনার্স ৩য় বর্ষ,1,লোক প্রশাসন বিভাগ,অনার্স ৩য় বর্ষ,,"[লোক প্রশাসন বিভাগ, অনার্স ৩য় বর্ষ]",2
772,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ: অনার্স ৩য় বর্ষ,1,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ,অনার্স ৩য় বর্ষ,,"[ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ, অনার্স ৩য় ব...",2
804,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ: অনার্স ৪র্থ বর্ষ,1,ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ,অনার্স ৪র্থ বর্ষ,,"[ইসলামের ইতিহাস ও সংস্কৃতি বিভাগ, অনার্স ৪র্থ...",2

In [ ]:
category_counts_df.loc[category_counts_df['cat_1'].str.contains("নবম ও দশম", regex=True)]

,categories,count,cat_1,cat_2,cat_3,categories_split,category_length
122,নবম ও দশম (এসএসসি): কমন সাবজেক্ট,34,নবম ও দশম (এসএসসি),কমন সাবজেক্ট,,"[নবম ও দশম (এসএসসি), কমন সাবজেক্ট]",2
135,নবম ও দশম (এসএসসি): আবশ্যিক বিষয়,28,নবম ও দশম (এসএসসি),আবশ্যিক বিষয়,,"[নবম ও দশম (এসএসসি), আবশ্যিক বিষয়]",2
149,নবম ও দশম (বিজ্ঞান): পদার্থবিজ্ঞান পাঠ্য সহায়িকা,26,নবম ও দশম (বিজ্ঞান),পদার্থবিজ্ঞান পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), পদার্থবিজ্ঞান পাঠ্য সহা...",2
162,নবম ও দশম (বিজ্ঞান): রসায়ন পাঠ্য সহায়িকা,23,নবম ও দশম (বিজ্ঞান),রসায়ন পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), রসায়ন পাঠ্য সহায়িকা]",2
207,নবম ও দশম (এসএসসি): বিজ্ঞান বিভাগ,19,নবম ও দশম (এসএসসি),বিজ্ঞান বিভাগ,,"[নবম ও দশম (এসএসসি), বিজ্ঞান বিভাগ]",2
243,নবম ও দশম (এসএসসি): ব্যবসায় শিক্ষা বিভাগ,14,নবম ও দশম (এসএসসি),ব্যবসায় শিক্ষা বিভাগ,,"[নবম ও দশম (এসএসসি), ব্যবসায় শিক্ষা বিভাগ]",2
248,নবম ও দশম (এসএসসি): বিজ্ঞান বিভাগ পাঠ্য সহায়িকা,13,নবম ও দশম (এসএসসি),বিজ্ঞান বিভাগ পাঠ্য সহায়িকা,,"[নবম ও দশম (এসএসসি), বিজ্ঞান বিভাগ পাঠ্য সহায...",2
273,নবম ও দশম (এসএসসি): মানবিক বিভাগ পাঠ্য সহায়িকা,11,নবম ও দশম (এসএসসি),মানবিক বিভাগ পাঠ্য সহায়িকা,,"[নবম ও দশম (এসএসসি), মানবিক বিভাগ পাঠ্য সহায়...",2
279,নবম ও দশম (বিজ্ঞান): জীববিজ্ঞান পাঠ্য সহায়িকা,11,নবম ও দশম (বিজ্ঞান),জীববিজ্ঞান পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), জীববিজ্ঞান পাঠ্য সহায়িকা]",2
336,নবম ও দশম (এসএসসি): ব্যবসায় শিক্ষা বিভাগ পাঠ্...,8,নবম ও দশম (এসএসসি),ব্যবসায় শিক্ষা বিভাগ পাঠ্য সহায়িকা,,"[নবম ও দশম (এসএসসি), ব্যবসায় শিক্ষা বিভাগ পা...",2
402,নবম ও দশম (বিজ্ঞান): উচ্চতর গণিত পাঠ্য সহায়িকা,5,নবম ও দশম (বিজ্ঞান),উচ্চতর গণিত পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), উচ্চতর গণিত পাঠ্য সহায়...",2
495,নবম ও দশম (এসএসসি): মানবিক বিভাগ,3,নবম ও দশম (এসএসসি),মানবিক বিভাগ,,"[নবম ও দশম (এসএসসি), মানবিক বিভাগ]",2
499,নবম ও দশম (ব্যবসায় শিক্ষা): হিসাববিজ্ঞান পাঠ্য...,3,নবম ও দশম (ব্যবসায় শিক্ষা),হিসাববিজ্ঞান পাঠ্য সহায়িকা,,"[নবম ও দশম (ব্যবসায় শিক্ষা), হিসাববিজ্ঞান পাঠ...",2
559,নবম ও দশম (মানবিক): অর্থনীতি পাঠ্য সহায়িকা,2,নবম ও দশম (মানবিক),অর্থনীতি পাঠ্য সহায়িকা,,"[নবম ও দশম (মানবিক), অর্থনীতি পাঠ্য সহায়িকা]",2
566,নবম ও দশম (মানবিক): পৌরনীতি ও নাগরিকতা পাঠ্য স...,2,নবম ও দশম (মানবিক),পৌরনীতি ও নাগরিকতা পাঠ্য সহায়িকা,,"[নবম ও দশম (মানবিক), পৌরনীতি ও নাগরিকতা পাঠ্য...",2
716,নবম ও দশম (বিজ্ঞান): গণিত পাঠ্য সহায়িকা,1,নবম ও দশম (বিজ্ঞান),গণিত পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), গণিত পাঠ্য সহায়িকা]",2
729,নবম ও দশম (এসএসসি): ঐচ্ছিক বিষয়,1,নবম ও দশম (এসএসসি),ঐচ্ছিক বিষয়,,"[নবম ও দশম (এসএসসি), ঐচ্ছিক বিষয়]",2
757,নবম ও দশম (বিজ্ঞান):আইসিটি পাঠ্য সহায়িকা,1,নবম ও দশম (বিজ্ঞান),আইসিটি পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), আইসিটি পাঠ্য সহায়িকা]",2
789,নবম ও দশম (মানবিক): ইংরেজি পাঠ্য সহায়িকা,1,নবম ও দশম (মানবিক),ইংরেজি পাঠ্য সহায়িকা,,"[নবম ও দশম (মানবিক), ইংরেজি পাঠ্য সহায়িকা]",2
795,নবম ও দশম (মানবিক): বাংলাদেশের ইতিহাস ও বিশ্বস...,1,নবম ও দশম (মানবিক),বাংলাদেশের ইতিহাস ও বিশ্বসভ্যতা পাঠ্য সহায়িকা,,"[নবম ও দশম (মানবিক), বাংলাদেশের ইতিহাস ও বিশ্...",2
796,নবম ও দশম (ব্যবসায় শিক্ষা): ব্যবসায় উদ্যোগ পাঠ...,1,নবম ও দশম (ব্যবসায় শিক্ষা),ব্যবসায় উদ্যোগ পাঠ্য সহায়িকা,,"[নবম ও দশম (ব্যবসায় শিক্ষা), ব্যবসায় উদ্যোগ প...",2
798,নবম ও দশম (মানবিক): ভূগোল ও পরিবেশ পাঠ্য সহায়িকা,1,নবম ও দশম (মানবিক),ভূগোল ও পরিবেশ পাঠ্য সহায়িকা,,"[নবম ও দশম (মানবিক), ভূগোল ও পরিবেশ পাঠ্য সহা...",2
799,"নবম ও দশম (ব্যবসায় শিক্ষা): ফিন্যান্স, ব্যাংকি...",1,নবম ও দশম (ব্যবসায় শিক্ষা),"ফিন্যান্স, ব্যাংকিং ও বিমা পাঠ্য সহায়িকা",,"[নবম ও দশম (ব্যবসায় শিক্ষা), ফিন্যান্স, ব্যাং...",2
800,নবম ও দশম (বিজ্ঞান): ধর্ম ও নৈতিক শিক্ষা পাঠ্য...,1,নবম ও দশম (বিজ্ঞান),ধর্ম ও নৈতিক শিক্ষা পাঠ্য সহায়িকা,,"[নবম ও দশম (বিজ্ঞান), ধর্ম ও নৈতিক শিক্ষা পাঠ...",2
803,নবম ও দশম (ব্যবসায় শিক্ষা): বাংলাদেশ ও বিশ্ব প...,1,নবম ও দশম (ব্যবসায় শিক্ষা),বাংলাদেশ ও বিশ্ব পরিচয় পাঠ্য সহায়িকা,,"[নবম ও দশম (ব্যবসায় শিক্ষা), বাংলাদেশ ও বিশ্ব...",2